import type { AsyncResult } from '@raghava.indra/result-ts';
import type { AppError } from '@core/errors/app-error';
import type * as F from '../models/finance';
type Result<T> = AsyncResult<T, AppError>;
export interface IFinanceRepo {
  books(): Result<F.Book[]>;
  catalog(bookId: string): Result<F.Catalog>;
  balances(bookId: string): Result<F.Balance[]>;
  transactions(bookId: string, query: F.TransactionQuery): Result<F.Transactions>;
  transaction(bookId: string, id: string): Result<F.Transaction>;
  plans(bookId: string): Result<F.Plans>;
  occurrences(bookId: string, from: string, to: string): Result<F.Occurrence[]>;
  imports(bookId: string, cursor?: string): Result<F.Imports>;
  importBatch(bookId: string, id: string): Result<F.ImportBatch>;
  rules(bookId: string): Result<F.Rule[]>;
  changes(bookId: string, cursor?: string): Result<F.Changes>;
  reconciliations(bookId: string): Result<F.Reconciliation[]>;
  report(bookId: string, from: string, to: string): Result<F.Report>;
  forecast(bookId: string, to: string): Result<F.Forecast>;
  suggestions(bookId: string): Result<F.Suggestions>;
  export(bookId: string, input: { format: 'JSON' | 'CSV'; from?: string; to?: string; includeDeleted?: boolean }): Result<F.FinanceExport>;
  createBook(input: F.CreateBook): Result<F.Book>;
  updateBook(bookId: string, input: F.UpdateBook): Result<F.Book>;
  createAccount(bookId: string, input: F.CreateAccount): Result<F.Account>;
  updateAccount(bookId: string, id: string, input: F.UpdateAccount): Result<F.Account>;
  createCategory(bookId: string, input: F.CreateCategory): Result<F.Category>;
  updateCategory(bookId: string, id: string, input: F.UpdateCategory): Result<F.Category>;
  createTransaction(bookId: string, input: F.CreateTransaction): Result<F.Transaction>;
  updateTransaction(bookId: string, id: string, input: F.UpdateTransaction): Result<F.Transaction>;
  setDeleted(bookId: string, id: string, expectedVersion: number, deleted: boolean): Result<F.Transaction>;
  bulkCategorize(bookId: string, categoryId: string, items: { id: string; expectedVersion: number }[]): Result<F.Transaction[]>;
  createSchedule(bookId: string, input: F.CreateSchedule): Result<F.Schedule>;
  updateSchedule(bookId: string, id: string, input: F.UpdateSchedule): Result<F.Schedule>;
  updateOccurrence(bookId: string, input: F.UpdateOccurrence): Result<F.Occurrence>;
  matchPayment(bookId: string, input: F.MatchPayment): Result<F.Occurrence>;
  unmatchPayment(bookId: string, input: F.OccurrenceTarget & { movementId: string }): Result<F.Occurrence>;
  setBudget(bookId: string, input: F.SetBudget): Result<F.Budget>;
  setEstimate(bookId: string, input: F.SetEstimate): Result<F.Estimate | { deleted: true }>;
  setRule(bookId: string, input: F.SetRule): Result<F.Rule>;
  stageStatement(bookId: string, input: F.StageStatement): Result<F.ImportBatch>;
  stageCsv(bookId: string, input: F.StageCsv): Result<F.ImportBatch>;
  resolveImport(bookId: string, id: string, expectedVersion: number, rows: F.RowResolution[]): Result<F.ImportBatch>;
  commitImport(bookId: string, id: string, expectedVersion: number, acceptUnverified: boolean): Result<F.ImportBatch>;
  cancelImport(bookId: string, id: string, expectedVersion: number): Result<F.ImportBatch>;
  reconcile(bookId: string, input: { accountId: string; date: string; statementBalance: string; notes?: string }): Result<F.Reconciliation>;
  reopen(bookId: string, id: string, expectedVersion: number, reason: string): Result<{ reopenedIds: string[] }>;
}
