import { hashToken } from "../auth";
import { prisma } from "../prisma";

export interface AuthenticatedMcpUser {
  id: string;
  displayName: string;
}

/**
 * Validates the high-entropy MCP access token generated by an authenticated user.
 * User IDs and email addresses are never accepted as MCP credentials.
 */
export async function validateUserToken(token?: string): Promise<AuthenticatedMcpUser | null> {
  if (!token || !token.trim()) {
    return null;
  }

  const accessToken = await prisma.reader_mcp_access_token.findUnique({
    where: { tokenHash: hashToken(token.trim()) },
    include: {
      readerProfile: {
        select: {
          user: { select: { id: true, displayName: true } },
        },
      },
    },
  });

  return accessToken?.readerProfile.user ?? null;
}
