import { container, TYPES } from '@di/container';
import type { IVocabularyRepo } from '../repos/vocabulary-repo';
import type { VocabularyQuery, VocabularyUpdate } from '../models/db-vocabulary';
const repo = () => container.get<IVocabularyRepo>(TYPES.IVocabularyRepo);
export const getVocabulary = (params: VocabularyQuery = {}) => repo().getVocabulary(params);
export const readVocabulary = (id: string) => repo().readVocabulary(id);
export const createVocabulary = (params: { term: string }) => repo().createVocabulary(params);
export const updateVocabulary = (id: string, params: VocabularyUpdate) => repo().updateVocabulary(id, params);
export const saveVocabularyExplanation = (id: string, expectedVersion: number, markdown: string) => repo().saveExplanation(id, expectedVersion, markdown);
export const deleteVocabulary = (params: { vocabId: string; expectedVersion: number }) => repo().deleteVocabulary(params);
