import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { type Actor, type FinanceDb } from '../../finance/context';
import { budgetSchema, estimateSchema, occurrenceUpdateSchema, paymentSchema, scheduleSchema, scheduleUpdateSchema, uuid } from '../../finance/contract';
import { createSchedule, listPlans, matchPayment, occurrences, rangeSchema, setBudget, setEstimate, unmatchPayment, unmatchSchema, updateOccurrence, updateSchedule } from '../../finance/plan-service';
import { forecast, forecastSchema } from '../../finance/forecast-service';
import { financeTool, registerFinanceTool as register } from './finance-tool';

export function registerFinancePlanTools(server: McpServer, actor: Actor, db: FinanceDb) {
  const userId = actor.userId;
  register(server, 'finance_list_plans', 'Get recurring/one-off plans, budget targets and reviewed discretionary estimates. Budgets never enter forecasts.', { bookId: uuid }, ({ bookId }) => financeTool(() => listPlans(db, userId, bookId)));
  register(server, 'finance_create_schedule', 'Plan income, expense or transfer using an anchored calendar recurrence and low/expected/high decimal strings. MONTHLY keeps the original day; every 28 days is DAILY interval 28. Optional account/category remain book-scoped.', { bookId: uuid, schedule: scheduleSchema }, ({ bookId, schedule }) => financeTool(() => createSchedule(db, actor, bookId, schedule)));
  register(server, 'finance_update_schedule', 'Update/archive a plan with expectedVersion. Existing confirmed or matched bill snapshots are preserved, not rewritten.', { bookId: uuid, scheduleId: uuid, schedule: scheduleUpdateSchema }, ({ bookId, scheduleId, schedule }) => financeTool(() => updateSchedule(db, actor, bookId, scheduleId, schedule)));
  register(server, 'finance_list_occurrences', 'Calculate bills in a calendar range, including stored snapshots, skipped state, paid and remaining amounts. Reads do not create rows; virtual occurrences have version 0.', { bookId: uuid, range: rangeSchema }, ({ bookId, range }) => financeTool(() => occurrences(db, userId, bookId, range)));
  register(server, 'finance_update_occurrence', 'Confirm actual bill amounts or skip/restore one occurrence by schedule ID and date. expectedVersion 0 identifies a virtual bill; use the returned version thereafter.', { bookId: uuid, occurrence: occurrenceUpdateSchema }, ({ bookId, occurrence }) => financeTool(() => updateOccurrence(db, actor, bookId, occurrence)));
  register(server, 'finance_match_payment', 'Link part or all of a posted movement to a bill. Direction/account/kind and total allocated capacity are checked. This only matches existing money, never creates another expense.', { bookId: uuid, payment: paymentSchema }, ({ bookId, payment }) => financeTool(() => matchPayment(db, actor, bookId, payment)));
  register(server, 'finance_unmatch_payment', 'Remove a bill’s payment link without deleting the actual transaction. Requires the current occurrence version.', { bookId: uuid, payment: unmatchSchema }, ({ bookId, payment }) => financeTool(() => unmatchPayment(db, actor, bookId, payment)));
  register(server, 'finance_set_budget', 'Set a monthly category spending target. expectedVersion 0 creates; later edits require current version. Zero disables spending allowance. This is not a forecast.', { bookId: uuid, budget: budgetSchema }, ({ bookId, budget }) => financeTool(() => setBudget(db, actor, bookId, budget)));
  register(server, 'finance_set_estimate', 'Set a reviewed monthly discretionary range EXCLUDING scheduled items. expectedVersion 0 creates. deleted=true removes the assumption with retained audit history.', { bookId: uuid, estimate: estimateSchema }, ({ bookId, estimate }) => financeTool(() => setEstimate(db, actor, bookId, estimate)));
  register(server, 'finance_forecast', 'Forecast daily cash from today in the book timezone through to (maximum two years), using unpaid plans, known/pending movements and reviewed estimates. Includes overdue obligations, assumption warnings and low/expected/high shortfall dates; budgets are excluded.', { bookId: uuid, forecast: forecastSchema }, ({ bookId, forecast: input }) => financeTool(() => forecast(db, userId, bookId, input)));
}
