import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { type Actor, type FinanceDb } from '../../finance/context';
import { commitImportSchema, importSchema, resolveImportSchema, uuid } from '../../finance/contract';
import { csvImportSchema } from '../../finance/import-csv';
import { cancelImport, cancelImportSchema, commitImport, getImport, importListSchema, listImports, resolveImport, stageImport } from '../../finance/import-service';
import { financeTool, registerFinanceTool as register } from './finance-tool';

export function registerFinanceImportTools(server: McpServer, actor: Actor, db: FinanceDb) {
  register(server, 'finance_list_imports', 'List statement-import batches and their status/checks. Continue with nextCursor. No statement is written directly into balances.', { bookId: uuid, query: importListSchema.optional() }, ({ bookId, query }) => financeTool(() => listImports(db, actor.userId, bookId, query ?? {})));
  register(server, 'finance_get_import', 'Get immutable extracted statement rows, current decisions, possible existing movement candidates and completeness checks before resolving or committing.', { bookId: uuid, importId: uuid }, ({ bookId, importId }) => financeTool(() => getImport(db, actor.userId, bookId, importId)));
  register(server, 'finance_stage_import', 'Stage at most 1000 exact signed-decimal rows extracted from a bank statement/PDF. Supply externalId ONLY for reliable stable bank IDs, not guessed fingerprints. Optional opening/closing balances, totals/count and period are checked. Transfers need the other counterpart account ID. This does not change the ledger.', { bookId: uuid, statement: importSchema }, ({ bookId, statement }) => financeTool(() => stageImport(db, actor, bookId, statement)));
  register(server, 'finance_stage_csv_import', 'Stage bounded CSV with explicitly mapped date/description and signed amount OR separate credit/debit columns. Date formats and grouping are explicit, never guessed. Preserve original source fields. Prefer structured staging after AI PDF extraction.', { bookId: uuid, statement: csvImportSchema }, ({ bookId, statement }) => financeTool(() => stageImport(db, actor, bookId, statement, true)));
  register(server, 'finance_resolve_import', 'Resolve draft rows as NEW, MATCH or SKIP with the current batch version. MATCH requires the exact account/signed amount/date. NEW duplicate candidates require explicit forceNew. You may specify categories, refund links and transfer counterpart account; no ledger writes yet.', { bookId: uuid, importId: uuid, changes: resolveImportSchema }, ({ bookId, importId, changes }) => financeTool(() => resolveImport(db, actor, bookId, importId, changes)));
  register(server, 'finance_commit_import', 'Atomically commit every resolved statement row once. Reject stale matches/duplicates or unresolved rows; roll back all rows on failure. Review completeness first: acceptUnverified is explicit and audited. Exact successful retries return the same result. Previously deleted imported money is never silently recreated.', { bookId: uuid, importId: uuid, confirmation: commitImportSchema }, ({ bookId, importId, confirmation }) => financeTool(() => commitImport(db, actor, bookId, importId, confirmation)));
  register(server, 'finance_cancel_import', 'Cancel a draft import without deleting extracted rows or source provenance. A corrected mapping may then stage the same file under a new request key. Committed transactions have separate recoverable deletion.', { bookId: uuid, importId: uuid, changes: cancelImportSchema }, ({ bookId, importId, changes }) => financeTool(() => cancelImport(db, actor, bookId, importId, changes)));
}
