import { useMemo, useState } from 'react';
import { observer } from 'mobx-react-lite';
import { Upload, Pencil, ArrowLeft } from 'lucide-react';
import { readCsv } from '@reader/finance-core';
import type * as F from '@domain/finance/models/finance';
import { Button } from '@modules/core/ui/primitives/button';
import type { FinanceStore } from '../store';
import { AccountOptions, CategoryOptions } from './catalog-forms';
import { FinanceHeader, Alert, Check, Empty, Field, FormDialog, Help, Input, Money, Section, Select, Textarea } from './common';
import { csvColumnLabels, displayDate, importCheckLabels, importDecisionLabels, importStatusLabels, shortDate } from '../format';

function ImportSteps({ step, complete = false }: { step: number; complete?: boolean }) {
  return <ol className="finance-import-steps" aria-label="Statement import progress">{['Upload statement', 'Review transactions', complete ? 'Imported' : 'Confirm import'].map((label, index) => <li key={index} aria-current={!complete && step === index + 1 ? 'step' : undefined} data-complete={complete || index + 1 < step}><span>{index + 1}</span>{label}</li>)}</ol>;
}

function CsvForm({ store, onClose }: { store: FinanceStore; onClose: () => void }) {
  const [requestKey] = useState(() => crypto.randomUUID());
  const [csv, setCsv] = useState(''), [separator, setSeparator] = useState<',' | ';' | '\t'>(','), [error, setError] = useState('');
  const [accountId, setAccount] = useState(''), [sourceName, setSource] = useState('Bank statement'), [signed, setSigned] = useState(true);
  const [mapping, setMapping] = useState<F.StageCsv['mapping']>({ date: '', description: '', dateFormat: 'YYYY-MM-DD', stripGrouping: false });
  const [metadata, setMetadata] = useState({ periodStart: '', periodEnd: '', openingBalance: '', closingBalance: '', totalCredits: '', totalDebits: '', expectedRowCount: '' });
  const parsed = useMemo(() => { try { return csv ? { data: readCsv(csv, separator), error: '' } : { data: null, error: '' }; } catch (cause) { return { data: null, error: (cause as Error).message }; } }, [csv, separator]);
  const loadFile = async (file?: File) => { if (!file) return; if (file.size > 2000000) { setError('Files must be 2 MB or smaller. Split larger statements without repeating rows.'); return; } setError(''); setCsv(await file.text()); setSource(file.name); };
  return <FormDialog store={store} title="Import a CSV statement" wide saveLabel="Prepare review" description="Match the columns and date format, then review the transactions. Nothing is added until you confirm the import. Your AI client can prepare PDF transactions through MCP." onClose={onClose} onSave={async () => {
    const result = await store.mutate(() => store.repo.stageCsv(store.bookId, { requestKey, accountId, sourceName, csv, separator, mapping: { ...mapping, amount: signed ? mapping.amount : undefined, credit: signed ? undefined : mapping.credit, debit: signed ? undefined : mapping.debit }, periodStart: metadata.periodStart || null, periodEnd: metadata.periodEnd || null, openingBalance: metadata.openingBalance || null, closingBalance: metadata.closingBalance || null, totalCredits: metadata.totalCredits || null, totalDebits: metadata.totalDebits || null, ...(metadata.expectedRowCount ? { expectedRowCount: Number(metadata.expectedRowCount) } : {}) }), 'Statement ready for review');
    if (!result) return false; await store.openImport(result.id); return true;
  }}><div className="finance-form-stack">{error && <Alert error>{error}</Alert>}<div className="finance-form-grid"><Field label="Account"><Select required value={accountId} onChange={e => setAccount(e.target.value)}><option value="">Choose account</option><AccountOptions store={store} /></Select></Field><Field label="Source name"><Input required maxLength={255} value={sourceName} onChange={e => setSource(e.target.value)} /></Field><Field label="CSV file"><Input type="file" accept=".csv,text/csv" onChange={e => void loadFile(e.target.files?.[0])} /></Field><Field label="Separator"><Select value={separator} onChange={e => setSeparator(e.target.value as typeof separator)}><option value=",">Comma</option><option value=";">Semicolon</option><option value={'\t'}>Tab</option></Select></Field></div><Field label="Or paste CSV"><Textarea rows={4} required maxLength={2000000} value={csv} onChange={e => setCsv(e.target.value)} /></Field>{parsed.error && <Alert error>{parsed.error}</Alert>}
    {parsed.data && <><p className="finance-note">{parsed.data.rows.length} rows. First five rows:</p><div className="finance-table-wrap"><table className="finance-table"><thead><tr>{parsed.data.headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{parsed.data.rows.slice(0, 5).map((row, index) => <tr key={index}>{row.map((value, i) => <td key={i}>{value}</td>)}</tr>)}</tbody></table></div><Check label="One signed amount column (positive credit, negative debit)" checked={signed} onChange={setSigned} /><div className="finance-form-grid">{(['date', 'description', ...(signed ? ['amount'] : ['credit', 'debit']), 'externalId', 'merchant', 'paymentMethod', 'bankReference'] as const).map(key => <Field key={key} label={csvColumnLabels[key]} hint={key === 'externalId' ? 'Use a unique bank transaction ID here, not a reference shared by several transactions.' : undefined}><Select required={['date', 'description', 'amount', 'credit', 'debit'].includes(key)} value={mapping[key as keyof typeof mapping] as string ?? ''} onChange={e => setMapping(old => ({ ...old, [key]: e.target.value || undefined }))}><option value="">Not mapped</option>{parsed.data!.headers.map(h => <option key={h} value={h}>{h}</option>)}</Select></Field>)}<Field label="Date format"><Select value={mapping.dateFormat} onChange={e => setMapping(old => ({ ...old, dateFormat: e.target.value as typeof mapping.dateFormat }))}><option>YYYY-MM-DD</option><option>DD-MM-YYYY</option><option>DD/MM/YYYY</option></Select></Field></div><Check label="Remove thousands separators (e.g. 1,000 or 1,00,000)" checked={mapping.stripGrouping} onChange={value => setMapping(old => ({ ...old, stripGrouping: value }))} /></>}
    <Help title="Statement dates and balance checks (recommended)"><div className="finance-form-grid">{Object.keys(metadata).map(key => <Field key={key} label={key.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase())}><Input type={key.startsWith('period') ? 'date' : key === 'expectedRowCount' ? 'number' : 'text'} min={key === 'expectedRowCount' ? 0 : undefined} value={metadata[key as keyof typeof metadata]} onChange={e => setMetadata(old => ({ ...old, [key]: e.target.value }))} /></Field>)}</div></Help></div></FormDialog>;
}
function ResolutionForm({ store, batch, row, onClose }: { store: FinanceStore; batch: F.ImportBatch; row: F.ImportRow; onClose: () => void }) {
  const original = { ...row.payload, ...row.resolution }, text = (key: string) => typeof original[key] === 'string' ? original[key] as string : '';
  const [decision, setDecision] = useState<'NEW' | 'MATCH' | 'SKIP'>(row.decision === 'UNRESOLVED' ? 'MATCH' : row.decision), [match, setMatch] = useState(text('matchMovementId')), [force, setForce] = useState(original.forceNew === true);
  const [kind, setKind] = useState<F.RowResolution['kind']>((text('kind') || (BigInt(row.amountMinor) > 0n ? 'INCOME' : 'EXPENSE')) as F.RowResolution['kind']);
  const [category, setCategory] = useState(text('categoryId')), [destination, setDestination] = useState(text('destinationAccountId')), [refund, setRefund] = useState(text('refundOfId')), [merchant, setMerchant] = useState(text('merchant'));
  return <FormDialog store={store} title={`Review statement row ${row.position + 1}`} description={`${shortDate(row.date)} · ${row.description}`} onClose={onClose} onSave={async () => { const result = await store.mutate(() => store.repo.resolveImport(store.bookId, batch.id, batch.version, [{ rowId: row.id, decision, ...(decision === 'MATCH' ? { matchMovementId: match } : {}), ...(decision === 'NEW' ? { kind, categoryId: kind === 'TRANSFER' ? null : category || null, destinationAccountId: kind === 'TRANSFER' ? destination || null : null, refundOfId: kind === 'REFUND' ? refund || null : null, merchant: merchant || null, forceNew: force } : {}) }])); if (!result) return false; await store.openImport(batch.id); return true; }}><div className="finance-form-stack"><p><Money book={store.book!} value={row.amountMinor} color /></p><Field label="Decision"><Select value={decision} onChange={e => setDecision(e.target.value as typeof decision)}><option value="NEW">Add a transaction</option><option value="MATCH">Match existing transaction</option><option value="SKIP">Skip this row</option></Select></Field>
    {decision === 'MATCH' && <><Field label="Matching account entry"><Select value={match} onChange={e => setMatch(e.target.value)}><option value="">Choose an entry or paste its ID below</option>{batch.candidates.filter(c => row.candidateIds.includes(c.id)).map(c => <option value={c.id} key={c.id}>{c.transaction.description}{c.transaction.deletedAt ? ' (deleted; will not be restored)' : ''} · {shortDate(c.effectiveDate)}</option>)}</Select></Field><Field label="Account entry ID" hint="Copy the entry ID from transaction details. Account, amount and date must match exactly."><Input required value={match} onChange={e => setMatch(e.target.value)} /></Field></>}
    {decision === 'NEW' && <><Field label="Type"><Select value={kind} onChange={e => { setKind(e.target.value as typeof kind); setCategory(''); }}><option value="EXPENSE">Expense</option><option value="INCOME">Income</option><option value="REFUND">Expense refund</option><option value="TRANSFER">Transfer</option></Select></Field>{kind === 'TRANSFER' ? <Field label="Counterpart account" hint="Also creates an entry in the other account. Match that entry when importing its statement."><Select required value={destination} onChange={e => setDestination(e.target.value)}><option value="">Choose counterpart</option><AccountOptions store={store} /></Select></Field> : <Field label="Category"><Select value={category} onChange={e => setCategory(e.target.value)}><option value="">Uncategorized</option><CategoryOptions store={store} kind={kind === 'INCOME' ? 'INCOME' : 'EXPENSE'} /></Select></Field>}<Field label="Merchant"><Input maxLength={255} value={merchant} onChange={e => setMerchant(e.target.value)} /></Field>{kind === 'REFUND' && <Field label="Original expense ID (optional)"><Input value={refund} onChange={e => setRefund(e.target.value)} /></Field>}<Check label="I checked the possible duplicates. This is a separate payment." checked={force} onChange={setForce} /></>}
    <details><summary>Original statement data</summary><pre className="finance-source">{JSON.stringify(row.payload, null, 2)}</pre></details></div></FormDialog>;
}
export const ImportsPanel = observer(function ImportsPanel({ store }: { store: FinanceStore }) {
  const [stage, setStage] = useState(false), [edit, setEdit] = useState<F.ImportRow | null>(null), [commit, setCommit] = useState(false), [cancel, setCancel] = useState(false), [accept, setAccept] = useState(false);
  const batch = store.selectedImport, disabled = store.readOnly || store.busy;
  return <>{batch ? <><FinanceHeader title={batch.sourceName} store={store} subtitle={`${store.catalog?.accounts.find(a => a.id === batch.accountId)?.name ?? ''} · ${importStatusLabels[batch.status]}`} actions={<Button variant="outlined" size="sm" onClick={store.closeImport}><ArrowLeft size={15} /> All imports</Button>} />
    {batch.status !== 'CANCELLED' ? <ImportSteps step={batch.status === 'COMMITTED' || commit ? 3 : 2} complete={batch.status === 'COMMITTED'} /> : <Alert>This draft was cancelled. No transactions were added by this draft.</Alert>}
    {batch.summary && <Section title="Statement checks"><div className="finance-card-body finance-form-stack">{batch.summary.warning && <Alert>{batch.summary.warning}</Alert>}<div className="finance-actions">{Object.entries(batch.summary.checks).map(([name, value]) => <span className={`finance-badge ${value === false ? 'finance-badge-error' : value === true ? 'finance-badge-success' : ''}`} key={name}>{importCheckLabels[name] ?? name}: {value === null ? 'Not provided' : value ? 'Matches' : 'Doesn’t match'}</span>)}</div><div className="finance-import-totals"><span><strong>{batch.summary.rowCount}</strong> rows</span><span>Money in <Money book={store.book!} value={batch.summary.calculatedCreditMinor} /></span><span>Money out <Money book={store.book!} value={batch.summary.calculatedDebitMinor} /></span></div></div></Section>}
    <Section title={batch.status === 'DRAFT' ? 'Review transactions' : 'Statement transactions'} subtitle={batch.status === 'DRAFT' ? `${batch.rows.filter(r => r.decision === 'UNRESOLVED').length} rows need a decision. Check duplicates and the other account for transfers.` : `${batch.rows.length} source rows`} actions={batch.status === 'DRAFT' ? <><Button variant="outlined" size="sm" disabled={disabled} onClick={() => setCancel(true)}>Cancel draft</Button><Button size="sm" disabled={disabled || batch.rows.some(r => r.decision === 'UNRESOLVED')} onClick={() => { setAccept(false); setCommit(true); }}>Confirm import</Button></> : undefined}><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Row / date</th><th>Original description</th><th className="finance-number">Amount</th><th>Decision</th><th /></tr></thead><tbody>{batch.rows.map(row => <tr key={row.id}><td>{row.position + 1}<small>{displayDate(row.date)}</small></td><td>{row.description}<small>{row.externalId ? `Bank ID: ${row.externalId}` : 'No unique bank ID'}</small></td><td className="finance-number"><Money book={store.book!} value={row.amountMinor} color /></td><td><span className={`finance-badge ${row.decision === 'UNRESOLVED' ? 'finance-badge-error' : ''}`}>{importDecisionLabels[row.decision]}</span><small>{row.candidateIds.length} possible matches{row.resolution?.categoryId ? ` · ${store.catalog?.categories.find(c => c.id === row.resolution?.categoryId)?.name ?? 'Suggested category'}` : ''}</small>{row.committedMovementId && <Help title="Account entry ID"><p className="finance-note">{row.committedMovementId}</p></Help>}</td><td>{batch.status === 'DRAFT' && <Button variant="ghost" iconOnly size="sm" disabled={disabled} aria-label={`Review row ${row.position + 1}`} tooltip="Review row" onClick={() => setEdit(row)}><Pencil size={15} /></Button>}</td></tr>)}</tbody></table></div></Section>
    {edit && <ResolutionForm store={store} batch={batch} row={edit} onClose={() => setEdit(null)} />}{commit && <FormDialog store={store} title="Confirm this import?" saveLabel="Confirm import" description="All reviewed rows are imported together. Retrying the same import won’t add them twice." onClose={() => setCommit(false)} onSave={async () => { const result = await store.mutate(() => store.repo.commitImport(store.bookId, batch.id, batch.version, accept), 'Statement imported'); if (!result) return false; await store.openImport(batch.id); return true; }}><div className="finance-form-stack"><p>{batch.rows.filter(r => r.decision === 'NEW').length} new · {batch.rows.filter(r => r.decision === 'MATCH').length} matched · {batch.rows.filter(r => r.decision === 'SKIP').length} skipped.</p>{!batch.balanceVerified && <><Alert error>We can’t confirm this statement is complete. Check for missing rows and balance mismatches before importing.</Alert><Check label="I checked the source statement and want to import despite unverified completeness." checked={accept} onChange={setAccept} /></>}<p className="finance-note">Imported entries are marked cleared. Check the account’s closing balance separately under History.</p></div></FormDialog>}{cancel && <FormDialog store={store} title="Cancel this import draft?" saveLabel="Cancel draft" description="The source rows and review history will remain. This draft hasn’t added any transactions." onClose={() => setCancel(false)} onSave={async () => { const result = await store.mutate(() => store.repo.cancelImport(store.bookId, batch.id, batch.version)); if (!result) return false; await store.openImport(batch.id); return true; }}><p>You can start a new import with corrected column mapping.</p></FormDialog>}
    </> : <><FinanceHeader store={store} title="Imports" subtitle="Bring in a statement without entering every transaction." actions={<Button size="sm" disabled={disabled || !store.activeAccounts.length} onClick={() => setStage(true)}><Upload size={15} /> Upload CSV</Button>} />
      <ImportSteps step={1} />
      {!store.activeAccounts.length && <Alert>Add an account before uploading its statement. <Button variant="ghost" size="sm" onClick={() => store.setTab('accounts')}>Go to Accounts</Button></Alert>}
      <Section title="Your statements" subtitle="Drafts don’t affect your balances until you confirm them.">{store.imports.items.map(item => <div className="finance-row" key={item.id}><div><strong>{item.sourceName}</strong><p>{store.catalog?.accounts.find(a => a.id === item.accountId)?.name} · {displayDate(item.createdAt)}</p><p>{item.balanceVerified ? 'Balances match' : 'Completeness unverified'}</p></div><div className="finance-actions"><span className={`finance-badge ${item.status === 'COMMITTED' ? 'finance-badge-success' : ''}`}>{importStatusLabels[item.status]}</span><Button variant="outlined" size="sm" onClick={() => void store.openImport(item.id)}>{item.status === 'DRAFT' ? 'Continue review' : 'View statement'}</Button></div></div>)}{!store.imports.items.length && <Empty title="Your first statement starts here" description="Upload a CSV, review duplicates and categories, then confirm. Nothing is added before you’re ready." />}{store.imports.nextCursor && <div className="finance-list-actions"><Button variant="outlined" size="sm" disabled={store.loading} onClick={() => void store.moreImports()}>Load more imports</Button></div>}</Section>
      <Help title="Have a PDF statement?"><p>Your connected AI client can read the PDF and prepare transactions through the same MCP connection. Review the prepared statement here before confirming it.</p></Help>
    </>}
    {stage && <CsvForm store={store} onClose={() => setStage(false)} />}
  </>;
});
