import { useState } from 'react';
import { observer } from 'mobx-react-lite';
import { Pencil, Plus, Trash2, RotateCcw, Eye, SlidersHorizontal } from 'lucide-react';
import type * as F from '@domain/finance/models/finance';
import { Button } from '@modules/core/ui/primitives/button';
import type { FinanceStore } from '../store';
import { displayDate, titleCase, transactionNet, transactionKindLabels } from '../format';
import { AccountForm, AccountOptions, CategoryOptions } from './catalog-forms';
import { Alert, Check, Empty, Field, FinanceHeader, FormDialog, Help, Input, Money, Select } from './common';
import { TransactionForm } from './transaction-form';
import { FinanceMarkdown } from './markdown';

export const AccountsPanel = observer(function AccountsPanel({ store }: { store: FinanceStore }) {
  const [edit, setEdit] = useState<F.Account | 'new' | null>(null);
  return <><FinanceHeader store={store} title="Accounts" subtitle="Bank accounts, cash, wallets and money you owe." actions={<Button disabled={store.readOnly || store.busy} size="sm" onClick={() => setEdit('new')}><Plus size={15} /> Add account</Button>} />
    <Help title="What do these balances mean?"><p><strong>Recorded balance</strong> includes all posted entries, including future-dated ones. <strong>Pending</strong> is separate. <strong>Cleared</strong> includes entries confirmed on a statement or in cash.</p><p>Cash forecasts start from today’s posted cash, not future-dated entries. Debt balances are usually negative.</p></Help>
    {!store.balances.length ? <div className="finance-card"><Empty title="Add your first account" description="Use any name: Savings, Cash, Wallet or Loan." action={<Button size="sm" disabled={store.readOnly || store.busy} onClick={() => setEdit('new')}>Add account</Button>} /></div> : <div className="finance-account-grid">{store.balances.map(item => <article className="finance-account-card" key={item.id}><div className="finance-account-heading"><div><h2>{item.name}</h2><p>{item.tracksDebt ? 'Debt account' : item.isLiquid ? 'Included in cash forecasts' : 'Outside cash forecasts'}{item.archivedAt ? ' · Archived' : ''}</p></div><Button variant="ghost" iconOnly size="sm" aria-label={`Edit ${item.name}`} tooltip="Edit account" disabled={store.readOnly || store.busy} onClick={() => setEdit(item)}><Pencil size={15} /></Button></div><div className="finance-account-balance"><small>Recorded balance</small><Money book={store.book!} value={item.postedMinor} color /></div><dl className="finance-account-meta"><div><dt>Pending</dt><dd><Money book={store.book!} value={item.pendingMinor} /></dd></div><div><dt>Cleared</dt><dd><Money book={store.book!} value={item.clearedMinor} /></dd></div></dl></article>)}</div>}
  {edit && <AccountForm store={store} existing={edit === 'new' ? undefined : edit} onClose={() => setEdit(null)} />}</>;
});
export const RegisterPanel = observer(function RegisterPanel({ store }: { store: FinanceStore }) {
  const [edit, setEdit] = useState<F.Transaction | 'new' | null>(null), [remove, setRemove] = useState<F.Transaction | null>(null), [view, setView] = useState<F.Transaction | null>(null);
  const [query, setQuery] = useState<F.TransactionQuery>(store.transactionQuery), [selected, setSelected] = useState<string[]>([]), [bulk, setBulk] = useState(false), [category, setCategory] = useState('');
  const [filtersOpen, setFiltersOpen] = useState(false);
  const extraCount = [query.categoryId, query.kind, query.status, query.paymentMethod, query.deleted].filter(Boolean).length;
  const clearFilters = () => { setQuery({}); setSelected([]); store.setTransactionQuery({}); };
  return <><FinanceHeader store={store} title="Transactions" subtitle="Your money in, money out and transfers." actions={<Button size="sm" disabled={store.readOnly || store.busy || !store.activeAccounts.length} onClick={() => setEdit('new')}><Plus size={15} /> Add transaction</Button>} />
    {!store.activeAccounts.length && <Alert>Add an account before recording a transaction. <Button size="sm" variant="ghost" onClick={() => store.setTab('accounts')}>Go to Accounts</Button></Alert>}
    <div className="finance-card"><form className="finance-filter-form" onSubmit={e => { e.preventDefault(); setSelected([]); store.setTransactionQuery(query); }}>
      <div className="finance-filter-bar"><Field label="Search"><Input type="search" placeholder="Search transactions…" value={query.search ?? ''} onChange={e => setQuery({ ...query, search: e.target.value || undefined })} /></Field><Field label="Account"><Select value={query.accountId ?? ''} onChange={e => setQuery({ ...query, accountId: e.target.value || undefined })}><option value="">All accounts</option><AccountOptions store={store} includeArchived /></Select></Field><Field label="From"><Input type="date" value={query.from ?? ''} onChange={e => setQuery({ ...query, from: e.target.value || undefined })} /></Field><Field label="To"><Input type="date" min={query.from} value={query.to ?? ''} onChange={e => setQuery({ ...query, to: e.target.value || undefined })} /></Field><div className="finance-actions"><Button type="button" size="sm" variant="outlined" aria-expanded={filtersOpen} aria-controls="finance-more-filters" onClick={() => setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={14} /> Filters{extraCount ? ` (${extraCount})` : ''}</Button><Button type="submit" size="sm" disabled={store.busy}>Apply</Button></div></div>
      <div id="finance-more-filters" hidden={!filtersOpen}><div className="finance-extra-filters"><Field label="Category"><Select value={query.categoryId ?? ''} onChange={e => setQuery({ ...query, categoryId: e.target.value || undefined })}><option value="">All categories</option><CategoryOptions store={store} /></Select></Field><Field label="Type"><Select value={query.kind ?? ''} onChange={e => setQuery({ ...query, kind: (e.target.value || undefined) as F.TransactionKind | undefined })}><option value="">All types</option>{(['EXPENSE', 'INCOME', 'TRANSFER', 'REFUND', 'ADJUSTMENT'] as const).map(kind => <option key={kind} value={kind}>{transactionKindLabels[kind]}</option>)}</Select></Field><Field label="Status"><Select value={query.status ?? ''} onChange={e => setQuery({ ...query, status: (e.target.value || undefined) as F.TransactionQuery['status'] })}><option value="">Posted and pending</option><option value="POSTED">Posted</option><option value="PENDING">Pending</option></Select></Field><Field label="Payment method"><Input placeholder="e.g. UPI" value={query.paymentMethod ?? ''} onChange={e => setQuery({ ...query, paymentMethod: e.target.value || undefined })} /></Field><div className="finance-actions finance-full"><Check label="Include deleted transactions" checked={query.deleted ?? false} onChange={value => setQuery({ ...query, deleted: value })} /><Button type="button" variant="ghost" size="sm" disabled={store.busy} onClick={clearFilters}>Clear all filters</Button></div></div></div>
    </form>
    {selected.length > 0 && <div className="finance-selection-bar"><strong>{selected.length} selected</strong><span>Up to 100 at a time</span><Button variant="ghost" size="sm" onClick={() => setSelected([])}>Clear</Button><Button size="sm" disabled={store.readOnly || store.busy} onClick={() => setBulk(true)}>Categorize</Button></div>}
    {!store.transactions.items.length ? <Empty title="No transactions found" description="Try another date range, clear the filters or add a transaction." action={<Button size="sm" variant="outlined" disabled={store.busy} onClick={clearFilters}>Clear filters</Button>} /> : <div className="finance-table-wrap"><table className="finance-table finance-register"><caption className="finance-sr-only">Transactions matching the applied filters</caption><thead><tr><th className="finance-select-cell"><span className="finance-sr-only">Select</span></th><th>Transaction</th><th>Account / category</th><th>Type</th><th className="finance-number">Amount</th><th><span className="finance-sr-only">Actions</span></th></tr></thead><tbody>{store.transactions.items.map(item => {
      // Transfers have a zero net change; show the amount moved, not zero.
      const amount = item.kind === 'TRANSFER' ? -item.movements.reduce((sum, m) => sum + (BigInt(m.amountMinor) < 0n ? BigInt(m.amountMinor) : 0n), 0n) : transactionNet(item);
      return <tr key={item.id} className={item.deletedAt ? 'finance-deleted-row' : undefined}>
        <td className="finance-select-cell"><Check compact label={`Select ${item.description}`} disabled={store.readOnly || store.busy || !!item.deletedAt || selected.length >= 100 && !selected.includes(item.id)} checked={selected.includes(item.id)} onChange={value => setSelected(ids => value ? [...ids, item.id] : ids.filter(id => id !== item.id))} /></td>
        <td><strong>{item.description}</strong><small>{displayDate(item.date)}{item.merchant ? ` · ${item.merchant}` : ''}{item.paymentMethod ? ` · ${item.paymentMethod}` : ''}</small></td>
        <td>{item.movements.map(m => <small key={m.id}>{store.catalog?.accounts.find(a => a.id === m.accountId)?.name} · <Money book={store.book!} value={m.amountMinor} />{m.reconciliationId ? ' · Locked' : m.cleared ? ' · Cleared' : ''}</small>)}<small>{item.splits.length ? item.splits.map(s => store.catalog?.categories.find(c => c.id === s.categoryId)?.name).join(', ') : item.kind === 'TRANSFER' || item.kind === 'ADJUSTMENT' ? 'Not income or spending' : 'Uncategorized'}</small></td>
        <td><span className="finance-badge">{transactionKindLabels[item.kind]}</span><small>{titleCase(item.status)}{item.deletedAt ? ' · Deleted' : ''}</small></td>
        <td className="finance-number"><strong><Money book={store.book!} value={amount} color={item.kind !== 'TRANSFER'} /></strong>{item.kind === 'TRANSFER' && <small>Between accounts</small>}</td>
        <td><div className="finance-actions finance-row-actions"><Button variant="ghost" iconOnly size="sm" aria-label={`Details for ${item.description}`} tooltip="View details" onClick={() => setView(item)}><Eye size={15} /></Button>{!item.deletedAt && <Button variant="ghost" iconOnly size="sm" aria-label={`Edit ${item.description}`} tooltip="Edit" disabled={store.readOnly || store.busy} onClick={() => setEdit(item)}><Pencil size={15} /></Button>}<Button variant="ghost" iconOnly size="sm" aria-label={`${item.deletedAt ? 'Restore' : 'Delete'} ${item.description}`} tooltip={item.deletedAt ? 'Restore' : 'Delete'} disabled={store.readOnly || store.busy} onClick={() => setRemove(item)}>{item.deletedAt ? <RotateCcw size={15} /> : <Trash2 size={15} />}</Button></div></td>
      </tr>;
    })}</tbody></table></div>}
    {store.transactions.nextCursor && <div className="finance-list-actions"><Button variant="outlined" size="sm" disabled={store.loading} onClick={() => void store.moreTransactions()}>Load more</Button></div>}
  </div>
  {edit && <TransactionForm store={store} existing={edit === 'new' ? undefined : edit} onClose={() => setEdit(null)} />}
  {remove && <FormDialog store={store} title={remove.deletedAt ? 'Restore transaction?' : 'Delete transaction?'} saveLabel={remove.deletedAt ? 'Restore' : 'Delete'} description={remove.description} onClose={() => setRemove(null)} onSave={async () => !!await store.mutate(() => store.repo.setDeleted(store.bookId, remove.id, remove.version, !remove.deletedAt))}><Alert>Deleting removes this transaction from balances and reports, but keeps its history and statement source. Remove payment links or reopen reconciled periods first.</Alert></FormDialog>}
  {bulk && <FormDialog store={store} title="Categorize selected transactions" onClose={() => setBulk(false)} onSave={async () => { const items = store.transactions.items.filter(t => selected.includes(t.id)).map(t => ({ id: t.id, expectedVersion: t.version })); const result = await store.mutate(() => store.repo.bulkCategorize(store.bookId, category, items)); if (!result) return false; setSelected([]); return true; }}><Field label="Category"><Select required value={category} onChange={e => setCategory(e.target.value)}><option value="">Choose category</option><CategoryOptions store={store} /></Select></Field><Alert>This replaces the category splits on all selected transactions. Transfers and balance corrections can’t be categorized.</Alert></FormDialog>}
  {view && <FormDialog store={store} title={view.description} saveLabel="Done" onClose={() => setView(null)} onSave={async () => true}>
    <dl className="finance-detail-list"><div><dt>Date</dt><dd>{displayDate(view.date)}</dd></div><div><dt>Type / status</dt><dd>{transactionKindLabels[view.kind]} · {titleCase(view.status)}</dd></div><div><dt>Merchant</dt><dd>{view.merchant || 'Not specified'}</dd></div><div><dt>Payment method</dt><dd>{view.paymentMethod || 'Not specified'}</dd></div><div><dt>Bank reference</dt><dd>{view.bankReference || 'None'}</dd></div><div><dt>Tags</dt><dd>{view.tags.join(', ') || 'None'}</dd></div></dl>
    <h3 className="finance-form-heading">Account entries</h3>{view.movements.map(m => <div className="finance-row" key={m.id}><div><strong>{store.catalog?.accounts.find(a => a.id === m.accountId)?.name}</strong><p>{displayDate(m.effectiveDate)} · {m.reconciliationId ? 'Locked' : m.cleared ? 'Cleared' : 'Uncleared'}</p><small className="finance-note">Entry ID: {m.id}</small></div><Money book={store.book!} value={m.amountMinor} color /></div>)}
    {view.notesMarkdown && <FinanceMarkdown source={view.notesMarkdown} />}
    {!!view.movements.flatMap(m => m.sourceRecords).length && <Help title="Original statement descriptions">{view.movements.flatMap(m => m.sourceRecords).map(s => <p key={s.id}>{s.sourceDescription}</p>)}</Help>}
    <Help title="Technical details"><p className="finance-note">Transaction ID: {view.id}</p><pre className="finance-source">{JSON.stringify(view, null, 2)}</pre></Help>
  </FormDialog>}
  </>;
});
