import { useState } from 'react';
import { observer } from 'mobx-react-lite';
import { Pencil, Plus, Trash2, RotateCcw, Eye } from 'lucide-react';
import type * as F from '@domain/finance/models/finance';
import { Button } from '@modules/core/ui/primitives/button';
import type { FinanceStore } from '../store';
import { shortDate, titleCase, transactionNet, transactionKindLabels } from '../format';
import { AccountForm, AccountOptions, CategoryOptions } from './catalog-forms';
import { Alert, Check, Empty, Field, FormDialog, Input, Money, Section, Select } from './common';
import { TransactionForm } from './transaction-form';
import { FinanceMarkdown } from './markdown';

export const AccountsPanel = observer(function AccountsPanel({ store }: { store: FinanceStore }) {
  const [edit, setEdit] = useState<F.Account | 'new' | null>(null);
  return <><Section store={store} title="Accounts" subtitle="Posted balances include all recorded dates. Pending amounts are separate. Forecasts start from today’s posted cash." actions={<Button disabled={store.readOnly || store.busy} size="sm" onClick={() => setEdit('new')}><Plus size={15} /> Add account</Button>}>
    {!store.balances.length ? <Empty title="No accounts yet" description="Add a bank account, wallet, cash or debt account." /> : <div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Account</th><th>Posted</th><th>Pending</th><th>Cleared</th><th /></tr></thead><tbody>{store.balances.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.tracksDebt ? 'Debt · ' : ''}{item.isLiquid ? 'Included in cash' : 'Not available cash'}{item.archivedAt ? ' · Archived' : ''}</small></td><td><Money book={store.book!} value={item.postedMinor} color /></td><td><Money book={store.book!} value={item.pendingMinor} /></td><td><Money book={store.book!} value={item.clearedMinor} /></td><td><Button variant="ghost" iconOnly size="sm" aria-label={`Edit ${item.name}`} disabled={store.readOnly || store.busy} onClick={() => setEdit(item)}><Pencil size={15} /></Button></td></tr>)}</tbody></table></div>}
  </Section>{edit && <AccountForm store={store} existing={edit === 'new' ? undefined : edit} onClose={() => setEdit(null)} />}</>;
});
export const RegisterPanel = observer(function RegisterPanel({ store }: { store: FinanceStore }) {
  const [edit, setEdit] = useState<F.Transaction | 'new' | null>(null), [remove, setRemove] = useState<F.Transaction | null>(null), [view, setView] = useState<F.Transaction | null>(null);
  const [query, setQuery] = useState<F.TransactionQuery>(store.transactionQuery), [selected, setSelected] = useState<string[]>([]), [bulk, setBulk] = useState(false), [category, setCategory] = useState('');
  return <><Section store={store} title="Transactions" actions={<Button size="sm" disabled={store.readOnly || store.busy || !store.activeAccounts.length} onClick={() => setEdit('new')}><Plus size={15} /> Add transaction</Button>}>
    <form className="finance-card-body finance-form-grid" onSubmit={e => { e.preventDefault(); setSelected([]); store.setTransactionQuery(query); }}>
      <Field label="Search"><Input placeholder="Description, merchant or reference" value={query.search ?? ''} onChange={e => setQuery({ ...query, search: e.target.value || undefined })} /></Field><Field label="Account"><Select value={query.accountId ?? ''} onChange={e => setQuery({ ...query, accountId: e.target.value || undefined })}><option value="">All accounts</option><AccountOptions store={store} includeArchived /></Select></Field><Field label="From"><Input type="date" value={query.from ?? ''} onChange={e => setQuery({ ...query, from: e.target.value || undefined })} /></Field><Field label="Through"><Input type="date" min={query.from} value={query.to ?? ''} onChange={e => setQuery({ ...query, to: e.target.value || undefined })} /></Field><Field label="Category"><Select value={query.categoryId ?? ''} onChange={e => setQuery({ ...query, categoryId: e.target.value || undefined })}><option value="">All categories</option><CategoryOptions store={store} /></Select></Field><Field label="Type"><Select value={query.kind ?? ''} onChange={e => setQuery({ ...query, kind: (e.target.value || undefined) as F.TransactionKind | undefined })}><option value="">All types</option>{(['EXPENSE', 'INCOME', 'TRANSFER', 'REFUND', 'ADJUSTMENT'] as const).map(kind => <option key={kind} value={kind}>{transactionKindLabels[kind]}</option>)}</Select></Field><Field label="Status"><Select value={query.status ?? ''} onChange={e => setQuery({ ...query, status: (e.target.value || undefined) as F.TransactionQuery['status'] })}><option value="">Posted and pending</option><option value="POSTED">Posted</option><option value="PENDING">Pending</option></Select></Field><Field label="Payment method"><Input value={query.paymentMethod ?? ''} onChange={e => setQuery({ ...query, paymentMethod: e.target.value || undefined })} /></Field><div className="finance-actions"><Check label="Show deleted transactions" checked={query.deleted ?? false} onChange={value => setQuery({ ...query, deleted: value })} /><Button type="submit" variant="outlined" size="sm" disabled={store.busy}>Apply filters</Button></div>
    </form>
    {selected.length > 0 && <div className="finance-row"><p>{selected.length} selected (maximum 100). Applying a category replaces the existing category splits.</p><Button size="sm" disabled={store.readOnly || store.busy} onClick={() => setBulk(true)}>Categorize</Button></div>}
    {!store.transactions.items.length ? <Empty title="No transactions in this view" description="Add a transaction, import a statement or change the filters." /> : <div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Select</th><th>Date / description</th><th>Type</th><th>Amount</th><th>Accounts / categories</th><th>Actions</th></tr></thead><tbody>{store.transactions.items.map(item => <tr key={item.id}><td><Check label={`Select ${item.description}`} disabled={store.readOnly || store.busy || !!item.deletedAt || selected.length >= 100 && !selected.includes(item.id)} checked={selected.includes(item.id)} onChange={value => setSelected(ids => value ? [...ids, item.id] : ids.filter(id => id !== item.id))} /></td><td><strong>{item.description}</strong><small>{shortDate(item.date)}{item.merchant ? ` · ${item.merchant}` : ''}{item.paymentMethod ? ` · ${item.paymentMethod}` : ''}</small></td><td><span className="finance-badge">{transactionKindLabels[item.kind]}</span><small>{titleCase(item.status)}{item.deletedAt ? ' · Deleted' : ''}</small></td><td><Money book={store.book!} value={transactionNet(item)} color /></td><td>{item.movements.map(m => <small key={m.id}>{store.catalog?.accounts.find(a => a.id === m.accountId)?.name} · <Money book={store.book!} value={m.amountMinor} />{m.reconciliationId ? ' · Locked' : m.cleared ? ' · Cleared' : ''}</small>)}<small>{item.splits.length ? item.splits.map(s => store.catalog?.categories.find(c => c.id === s.categoryId)?.name).join(', ') : item.kind === 'TRANSFER' || item.kind === 'ADJUSTMENT' ? 'Not income or spending' : 'Uncategorized'}</small></td><td><div className="finance-actions"><Button variant="ghost" iconOnly size="sm" aria-label={`Details for ${item.description}`} onClick={() => setView(item)}><Eye size={15} /></Button>{!item.deletedAt && <Button variant="ghost" iconOnly size="sm" aria-label={`Edit ${item.description}`} disabled={store.readOnly || store.busy} onClick={() => setEdit(item)}><Pencil size={15} /></Button>}<Button variant="ghost" iconOnly size="sm" aria-label={`${item.deletedAt ? 'Restore' : 'Delete'} ${item.description}`} disabled={store.readOnly || store.busy} onClick={() => setRemove(item)}>{item.deletedAt ? <RotateCcw size={15} /> : <Trash2 size={15} />}</Button></div></td></tr>)}</tbody></table></div>}
    {store.transactions.nextCursor && <div className="finance-list-actions"><Button variant="outlined" size="sm" disabled={store.loading} onClick={() => void store.moreTransactions()}>Load more</Button></div>}
  </Section>
  {edit && <TransactionForm store={store} existing={edit === 'new' ? undefined : edit} onClose={() => setEdit(null)} />}
  {remove && <FormDialog store={store} title={remove.deletedAt ? 'Restore transaction?' : 'Delete transaction?'} saveLabel={remove.deletedAt ? 'Restore' : 'Delete'} description={remove.description} onClose={() => setRemove(null)} onSave={async () => !!await store.mutate(() => store.repo.setDeleted(store.bookId, remove.id, remove.version, !remove.deletedAt))}><Alert>Deleting removes this transaction from balances and reports, but keeps its history and statement source. Remove payment links or reopen reconciled periods first.</Alert></FormDialog>}
  {bulk && <FormDialog store={store} title="Categorize selected transactions" onClose={() => setBulk(false)} onSave={async () => { const items = store.transactions.items.filter(t => selected.includes(t.id)).map(t => ({ id: t.id, expectedVersion: t.version })); const result = await store.mutate(() => store.repo.bulkCategorize(store.bookId, category, items)); if (!result) return false; setSelected([]); return true; }}><Field label="Category"><Select required value={category} onChange={e => setCategory(e.target.value)}><option value="">Choose category</option><CategoryOptions store={store} /></Select></Field><p className="finance-note">The category is applied to all selected transactions together. Transfers and balance corrections can’t be categorized.</p></FormDialog>}
  {view && <FormDialog store={store} title="Transaction details" saveLabel="Done" onClose={() => setView(null)} onSave={async () => true}><p className="finance-note">Transaction ID: {view.id}</p><p>{view.description}</p>{view.notesMarkdown && <FinanceMarkdown source={view.notesMarkdown} />}<p className="finance-note">Original descriptions from statements</p>{view.movements.flatMap(m => m.sourceRecords).map(s => <p key={s.id}>{s.sourceDescription}</p>)}<pre className="finance-source">{JSON.stringify(view, null, 2)}</pre></FormDialog>}
  </>;
});
