import { useState } from 'react';
import { observer } from 'mobx-react-lite';
import { Pencil, Plus } from 'lucide-react';
import { formatMoney } from '@reader/finance-core';
import type * as F from '@domain/finance/models/finance';
import { Button } from '@modules/core/ui/primitives/button';
import type { FinanceStore } from '../store';
import { BookForm, CategoryForm, CategoryOptions, AccountOptions } from './catalog-forms';
import { Alert, Check, Field, FormDialog, Input, Money, Section, Select, Textarea } from './common';
import { RangeFields } from './plan-panels';
import { auditActionLabels, auditEntityLabels, auditSourceLabels, shortDate } from '../format';

function BudgetForm({ store, existing, onClose }: { store: FinanceStore; existing?: F.Budget; onClose: () => void }) {
  const [categoryId, setCategory] = useState(existing?.categoryId ?? ''), [month, setMonth] = useState(existing?.month.slice(0, 7) ?? store.today.slice(0, 7)), [amount, setAmount] = useState(existing ? formatMoney(BigInt(existing.amountMinor), store.book!.currencyScale) : '');
  return <FormDialog store={store} title="Monthly budget" onClose={onClose} onSave={async () => { const old = store.plans.budgets.find(b => b.categoryId === categoryId && b.month.slice(0, 7) === month); return !!await store.mutate(() => store.repo.setBudget(store.bookId, { categoryId, month: `${month}-01`, amount, expectedVersion: old?.version ?? 0 })); }}><div className="finance-form-stack"><Field label="Expense category"><Select required value={categoryId} onChange={e => setCategory(e.target.value)}><option value="">Choose category</option><CategoryOptions store={store} kind="EXPENSE" /></Select></Field><Field label="Month"><Input required type="month" value={month} onChange={e => setMonth(e.target.value)} /></Field><Field label="Target amount" hint="Enter zero to clear the budget. Budgets don’t add forecast expenses."><Input required inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} /></Field></div></FormDialog>;
}
function EstimateForm({ store, existing, seed, onClose }: { store: FinanceStore; existing?: F.Estimate; seed?: F.Suggestions['estimates'][number]; onClose: () => void }) {
  const scale = store.book!.currencyScale, source = existing ?? seed;
  const [categoryId, setCategory] = useState(source?.categoryId ?? ''), [range, setRange] = useState({ low: source ? formatMoney(BigInt(source.lowMinor), scale) : '0', expected: source ? formatMoney(BigInt(source.expectedMinor), scale) : '0', high: source ? formatMoney(BigInt(source.highMinor), scale) : '0' }), [deleted, setDeleted] = useState(false);
  return <FormDialog store={store} title="Spending estimate" description="Estimate monthly spending not already covered by plans. Review the recorded history before saving; estimates aren’t guaranteed." onClose={onClose} onSave={async () => { const old = store.plans.estimates.find(e => e.categoryId === categoryId); return !!await store.mutate(() => store.repo.setEstimate(store.bookId, { categoryId, ...range, deleted, expectedVersion: old?.version ?? 0 })); }}><div className="finance-form-stack"><Field label="Expense category"><Select required disabled={!!existing} value={categoryId} onChange={e => setCategory(e.target.value)}><option value="">Choose category</option><CategoryOptions store={store} kind="EXPENSE" /></Select></Field><RangeFields {...range} onChange={(field, value) => setRange(old => ({ ...old, [field]: value }))} />{existing && <Check label="Exclude this estimate from forecasts" checked={deleted} onChange={setDeleted} />}{seed && <Alert>Spending recorded in {seed.monthsWithRecordedSpend} of the last six complete months, including months with no recorded spending. Check for missing records before saving.</Alert>}</div></FormDialog>;
}
function RuleForm({ store, existing, onClose }: { store: FinanceStore; existing?: F.Rule; onClose: () => void }) {
  const [id] = useState(() => existing?.id ?? crypto.randomUUID()), [categoryId, setCategory] = useState(existing?.categoryId ?? ''), [text, setText] = useState(existing?.matchText ?? ''), [merchant, setMerchant] = useState(existing?.merchantName ?? ''), [enabled, setEnabled] = useState(existing?.enabled ?? true);
  return <FormDialog store={store} title="Categorization rule" description="Suggest a category when imported descriptions match this text, ignoring case. Suggestions are reviewed before import. Existing transactions stay unchanged." onClose={onClose} onSave={async () => !!await store.mutate(() => store.repo.setRule(store.bookId, { id, expectedVersion: existing?.version ?? 0, categoryId, matchText: text, merchantName: merchant || null, enabled }))}><div className="finance-form-stack"><Field label="Description contains"><Input required maxLength={255} value={text} onChange={e => setText(e.target.value)} /></Field><Field label="Category"><Select required value={categoryId} onChange={e => setCategory(e.target.value)}><option value="">Choose category</option><CategoryOptions store={store} /></Select></Field><Field label="Merchant (optional)"><Input maxLength={255} value={merchant} onChange={e => setMerchant(e.target.value)} /></Field><Check label="Enabled" checked={enabled} onChange={setEnabled} /></div></FormDialog>;
}
export const ManagePanel = observer(function ManagePanel({ store }: { store: FinanceStore }) {
  const [book, setBook] = useState(false), [category, setCategory] = useState<F.Category | 'new' | null>(null), [budget, setBudget] = useState<F.Budget | 'new' | null>(null), [estimate, setEstimate] = useState<F.Estimate | 'new' | null>(null), [rule, setRule] = useState<F.Rule | 'new' | null>(null), [seed, setSeed] = useState<F.Suggestions['estimates'][number]>();
  const disabled = store.readOnly || store.busy;
  return <><Section store={store} title="Book settings" subtitle={`${store.book!.currency} · ${store.book!.timezone}`} actions={<Button size="sm" variant="outlined" disabled={store.busy} onClick={() => setBook(true)}>Book settings</Button>}><p className="finance-card-body finance-muted">Archived books are read-only. Their history stays available, and you can restore them here.</p></Section>
    <Section title="Categories" subtitle="Group income and expenses. Add subcategories if needed." actions={<Button size="sm" disabled={disabled} onClick={() => setCategory('new')}><Plus size={15} /> Add category</Button>}>{store.catalog?.categories.map(c => <div className="finance-row" key={c.id}><div><strong>{c.name}</strong><p>{c.kind === 'INCOME' ? 'Income' : 'Expense'}{c.parentId ? ` · Under ${store.catalog?.categories.find(p => p.id === c.parentId)?.name}` : ''}{c.archivedAt ? ' · Archived' : ''}</p></div><Button variant="ghost" iconOnly size="sm" disabled={disabled} aria-label={`Edit category ${c.name}`} onClick={() => setCategory(c)}><Pencil size={15} /></Button></div>)}</Section>
    <div className="finance-grid"><Section title="Budgets" subtitle="Set monthly budgets by category. They aren’t forecast expenses." actions={<Button size="sm" disabled={disabled} aria-label="Add budget" onClick={() => setBudget('new')}><Plus size={15} /></Button>}>{store.plans.budgets.map(b => <div className="finance-row" key={b.id}><div><strong>{store.catalog?.categories.find(c => c.id === b.categoryId)?.name}</strong><p>{b.month.slice(0, 7)}</p></div><div className="finance-actions"><Money book={store.book!} value={b.amountMinor} /><Button variant="ghost" iconOnly size="sm" disabled={disabled} aria-label="Edit budget" onClick={() => setBudget(b)}><Pencil size={15} /></Button></div></div>)}</Section><Section title="Spending estimates" subtitle="Monthly estimates for spending not covered by plans." actions={<Button size="sm" disabled={disabled} aria-label="Add spending estimate" onClick={() => { setSeed(undefined); setEstimate('new'); }}><Plus size={15} /></Button>}>{store.plans.estimates.map(e => <div className="finance-row" key={e.id}><div><strong>{store.catalog?.categories.find(c => c.id === e.categoryId)?.name}</strong><p><Money book={store.book!} value={e.lowMinor} /> / <Money book={store.book!} value={e.expectedMinor} /> / <Money book={store.book!} value={e.highMinor} /></p></div><Button variant="ghost" iconOnly size="sm" disabled={disabled} aria-label="Edit estimate" onClick={() => setEstimate(e)}><Pencil size={15} /></Button></div>)}</Section></div>
    <Section title="Categorization rules" subtitle="Suggest categories for imported transactions." actions={<Button size="sm" disabled={disabled} onClick={() => setRule('new')}><Plus size={15} /> Add rule</Button>}>{store.rules.map(r => <div className="finance-row" key={r.id}><div><strong>Contains “{r.matchText}”</strong><p>{store.catalog?.categories.find(c => c.id === r.categoryId)?.name}{r.merchantName ? ` · ${r.merchantName}` : ''}{!r.enabled ? ' · Disabled' : ''}</p></div><Button variant="ghost" iconOnly size="sm" disabled={disabled} aria-label={`Edit rule ${r.matchText}`} onClick={() => setRule(r)}><Pencil size={15} /></Button></div>)}</Section>
    <Section title="Suggested spending estimates" subtitle="Check for missing history and exclude bills already in your plans before saving." actions={<Button variant="outlined" size="sm" disabled={store.busy} onClick={() => void store.loadSuggestions()}>Review history</Button>}>{store.suggestions && <div className="finance-card-body finance-form-stack">{store.suggestions.warnings.map(w => <Alert key={w}>{w}</Alert>)}{store.suggestions.estimates.map(s => <div className="finance-row" key={s.categoryId}><div><strong>{s.categoryName}</strong><p>Recorded spending in {s.monthsWithRecordedSpend}/6 months · Expected <Money book={store.book!} value={s.expectedMinor} /></p></div><Button variant="outlined" size="sm" disabled={disabled} onClick={() => { setSeed(s); setEstimate('new'); }}>Review estimate</Button></div>)}</div>}</Section>
    {book && <BookForm store={store} existing={store.book!} onClose={() => setBook(false)} />}{category && <CategoryForm store={store} existing={category === 'new' ? undefined : category} onClose={() => setCategory(null)} />}{budget && <BudgetForm store={store} existing={budget === 'new' ? undefined : budget} onClose={() => setBudget(null)} />}{estimate && <EstimateForm store={store} existing={estimate === 'new' ? undefined : estimate} seed={seed} onClose={() => setEstimate(null)} />}{rule && <RuleForm store={store} existing={rule === 'new' ? undefined : rule} onClose={() => setRule(null)} />}
  </>;
});
function ReconcileForm({ store, onClose }: { store: FinanceStore; onClose: () => void }) {
  const [accountId, setAccount] = useState(''), [date, setDate] = useState(store.today), [balance, setBalance] = useState(''), [notes, setNotes] = useState('');
  return <FormDialog store={store} title="Reconcile a statement" description="Cleared, posted entries must match the statement’s closing balance. No transaction is added to make them match. Confirming locks this account period." onClose={onClose} onSave={async () => !!await store.mutate(() => store.repo.reconcile(store.bookId, { accountId, date, statementBalance: balance, notes }))}><div className="finance-form-stack"><Field label="Account"><Select required value={accountId} onChange={e => setAccount(e.target.value)}><option value="">Choose account</option><AccountOptions store={store} /></Select></Field><Field label="Statement through"><Input required type="date" value={date} onChange={e => setDate(e.target.value)} /></Field><Field label="Statement closing balance"><Input required inputMode="decimal" value={balance} onChange={e => setBalance(e.target.value)} /></Field><Field label="Notes"><Textarea rows={3} value={notes} onChange={e => setNotes(e.target.value)} /></Field></div></FormDialog>;
}
export const HistoryPanel = observer(function HistoryPanel({ store }: { store: FinanceStore }) {
  const [reconcile, setReconcile] = useState(false), [reopen, setReopen] = useState<F.Reconciliation | null>(null), [reason, setReason] = useState('');
  return <><Section store={store} title="Statement reconciliation" subtitle="Confirm a closing balance and lock the account period. Reopening is recorded in history." actions={<Button size="sm" disabled={store.readOnly || store.busy} onClick={() => setReconcile(true)}>Reconcile account</Button>}>{store.reconciliations.map(r => <div className="finance-row" key={r.id}><div><strong>{store.catalog?.accounts.find(a => a.id === r.accountId)?.name} · {shortDate(r.date)}</strong><p>{r.reopenedAt ? 'Reopened' : 'Locked'} · Statement <Money book={store.book!} value={r.statementMinor} /></p></div>{!r.reopenedAt && <Button variant="outlined" size="sm" disabled={store.readOnly || store.busy} onClick={() => { setReason(''); setReopen(r); }}>Reopen</Button>}</div>)}</Section><Section title="Change history" subtitle="Changes include their source and the values before and after.">{store.changes.items.map(c => <details className="finance-history" key={c.id}><summary>{c.createdAt.replace('T', ' ').slice(0, 19)} · {auditSourceLabels[c.source] ?? c.source} · {auditActionLabels[c.action] ?? c.action} {auditEntityLabels[c.entityType] ?? c.entityType}</summary><p className="finance-note">Entity {c.entityId}</p><div className="finance-grid"><div><h3>Before</h3><pre className="finance-source">{JSON.stringify(c.before, null, 2)}</pre></div><div><h3>After</h3><pre className="finance-source">{JSON.stringify(c.after, null, 2)}</pre></div></div></details>)}{store.changes.nextCursor && <div className="finance-list-actions"><Button variant="outlined" size="sm" disabled={store.loading} onClick={() => void store.moreChanges()}>Load more history</Button></div>}</Section>
    {reconcile && <ReconcileForm store={store} onClose={() => setReconcile(false)} />}{reopen && <FormDialog store={store} title="Reopen account period?" description="Later reconciliations that depend on this period will also reopen. Transactions and history stay unchanged." onClose={() => setReopen(null)} saveLabel="Reopen" onSave={async () => !!await store.mutate(() => store.repo.reopen(store.bookId, reopen.id, reopen.version, reason))}><Field label="Reason"><Textarea required maxLength={5000} rows={3} value={reason} onChange={e => setReason(e.target.value)} /></Field></FormDialog>}
  </>;
});
