import { useState } from 'react';
import { observer } from 'mobx-react-lite';
import { Pencil, Plus } from 'lucide-react';
import { formatMoney } from '@reader/finance-core';
import type * as F from '@domain/finance/models/finance';
import { Button } from '@modules/core/ui/primitives/button';
import type { FinanceStore } from '../store';
import { BookForm, CategoryForm, CategoryOptions, AccountOptions } from './catalog-forms';
import { Alert, AmountRange, Check, Empty, Field, FinanceHeader, FormDialog, Input, Money, Section, Select, Textarea, ViewTabs } from './common';
import { RangeFields } from './plan-panels';
import { auditActionLabels, auditEntityLabels, auditSourceLabels, displayDate, displayTimestamp } from '../format';
import { ChangeDetails, changeName } from './change-details';

function BudgetForm({ store, existing, onClose }: { store: FinanceStore; existing?: F.Budget; onClose: () => void }) {
  const [categoryId, setCategory] = useState(existing?.categoryId ?? ''), [month, setMonth] = useState(existing?.month.slice(0, 7) ?? store.today.slice(0, 7)), [amount, setAmount] = useState(existing ? formatMoney(BigInt(existing.amountMinor), store.book!.currencyScale) : '');
  return <FormDialog store={store} title="Monthly budget" onClose={onClose} onSave={async () => { const old = store.plans.budgets.find(b => b.categoryId === categoryId && b.month.slice(0, 7) === month); return !!await store.mutate(() => store.repo.setBudget(store.bookId, { categoryId, month: `${month}-01`, amount, expectedVersion: old?.version ?? 0 })); }}><div className="finance-form-stack"><Field label="Expense category"><Select required value={categoryId} onChange={e => setCategory(e.target.value)}><option value="">Choose category</option><CategoryOptions store={store} kind="EXPENSE" /></Select></Field><Field label="Month"><Input required type="month" value={month} onChange={e => setMonth(e.target.value)} /></Field><Field label="Target amount" hint="Enter zero to clear the budget. Budgets don’t add forecast expenses."><Input required inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} /></Field></div></FormDialog>;
}
function EstimateForm({ store, existing, seed, onClose }: { store: FinanceStore; existing?: F.Estimate; seed?: F.Suggestions['estimates'][number]; onClose: () => void }) {
  const scale = store.book!.currencyScale, source = existing ?? seed;
  const [categoryId, setCategory] = useState(source?.categoryId ?? ''), [range, setRange] = useState({ low: source ? formatMoney(BigInt(source.lowMinor), scale) : '0', expected: source ? formatMoney(BigInt(source.expectedMinor), scale) : '0', high: source ? formatMoney(BigInt(source.highMinor), scale) : '0' }), [deleted, setDeleted] = useState(false);
  return <FormDialog store={store} title="Spending estimate" description="Estimate monthly spending not already covered by plans. Review the recorded history before saving; estimates aren’t guaranteed." onClose={onClose} onSave={async () => { const old = store.plans.estimates.find(e => e.categoryId === categoryId); return !!await store.mutate(() => store.repo.setEstimate(store.bookId, { categoryId, ...range, deleted, expectedVersion: old?.version ?? 0 })); }}><div className="finance-form-stack"><Field label="Expense category"><Select required disabled={!!existing} value={categoryId} onChange={e => setCategory(e.target.value)}><option value="">Choose category</option><CategoryOptions store={store} kind="EXPENSE" /></Select></Field><RangeFields {...range} onChange={(field, value) => setRange(old => ({ ...old, [field]: value }))} />{existing && <Check label="Exclude this estimate from forecasts" checked={deleted} onChange={setDeleted} />}{seed && <Alert>Spending recorded in {seed.monthsWithRecordedSpend} of the last six complete months, including months with no recorded spending. Check for missing records before saving.</Alert>}</div></FormDialog>;
}
function RuleForm({ store, existing, onClose }: { store: FinanceStore; existing?: F.Rule; onClose: () => void }) {
  const [id] = useState(() => existing?.id ?? crypto.randomUUID()), [categoryId, setCategory] = useState(existing?.categoryId ?? ''), [text, setText] = useState(existing?.matchText ?? ''), [merchant, setMerchant] = useState(existing?.merchantName ?? ''), [enabled, setEnabled] = useState(existing?.enabled ?? true);
  return <FormDialog store={store} title="Categorization rule" description="Suggest a category when imported descriptions match this text, ignoring case. Suggestions are reviewed before import. Existing transactions stay unchanged." onClose={onClose} onSave={async () => !!await store.mutate(() => store.repo.setRule(store.bookId, { id, expectedVersion: existing?.version ?? 0, categoryId, matchText: text, merchantName: merchant || null, enabled }))}><div className="finance-form-stack"><Field label="Description contains"><Input required maxLength={255} value={text} onChange={e => setText(e.target.value)} /></Field><Field label="Category"><Select required value={categoryId} onChange={e => setCategory(e.target.value)}><option value="">Choose category</option><CategoryOptions store={store} /></Select></Field><Field label="Merchant (optional)"><Input maxLength={255} value={merchant} onChange={e => setMerchant(e.target.value)} /></Field><Check label="Enabled" checked={enabled} onChange={setEnabled} /></div></FormDialog>;
}
export const ManagePanel = observer(function ManagePanel({ store }: { store: FinanceStore }) {
  const [book, setBook] = useState(false), [category, setCategory] = useState<F.Category | 'new' | null>(null), [budget, setBudget] = useState<F.Budget | 'new' | null>(null), [estimate, setEstimate] = useState<F.Estimate | 'new' | null>(null), [rule, setRule] = useState<F.Rule | 'new' | null>(null), [seed, setSeed] = useState<F.Suggestions['estimates'][number]>();
  const disabled = store.readOnly || store.busy;
  const [view, setView] = useState<'categories' | 'budgets' | 'estimates' | 'rules' | 'book'>('categories');
  return <><FinanceHeader store={store} title="Manage" subtitle="Organize your book and fine-tune your spending plans." />
    <ViewTabs label="Book management" items={[{ id: 'categories', label: 'Categories' }, { id: 'budgets', label: 'Budgets' }, { id: 'estimates', label: 'Spending estimates' }, { id: 'rules', label: 'Import rules' }, { id: 'book', label: 'Book settings' }]} value={view} onChange={setView} />
    {view === 'book' && <Section title={store.book!.name} subtitle="Book settings" actions={<Button size="sm" variant="outlined" disabled={store.busy} onClick={() => setBook(true)}>Edit book</Button>}><dl className="finance-detail-list finance-card-body"><div><dt>Currency</dt><dd>{store.book!.currency}</dd></div><div><dt>Timezone</dt><dd>{store.book!.timezone}</dd></div><div><dt>Status</dt><dd>{store.readOnly ? 'Archived · Read-only' : 'Active'}</dd></div></dl><p className="finance-card-body finance-note">Archiving keeps your records and history. You can restore this book at any time.</p></Section>}
    {view === 'categories' && <Section title="Categories" subtitle="Group your income and expenses." actions={<Button size="sm" disabled={disabled} onClick={() => setCategory('new')}><Plus size={15} /> Add category</Button>}><div className="finance-category-grid">{(['EXPENSE', 'INCOME'] as const).map(kind => <div key={kind}><h3 className="finance-group-heading">{kind === 'EXPENSE' ? 'Expenses' : 'Income'}</h3>{store.catalog?.categories.filter(c => c.kind === kind).map(c => <div className="finance-row" key={c.id}><div><strong>{c.name}</strong><p>{c.parentId ? `Under ${store.catalog?.categories.find(p => p.id === c.parentId)?.name}` : 'Main category'}{c.archivedAt ? ' · Archived' : ''}</p></div><Button variant="ghost" iconOnly size="sm" disabled={disabled} aria-label={`Edit category ${c.name}`} tooltip="Edit category" onClick={() => setCategory(c)}><Pencil size={15} /></Button></div>)}{!store.catalog?.categories.some(c => c.kind === kind) && <p className="finance-card-body finance-muted">No categories yet.</p>}</div>)}</div></Section>}
    {view === 'budgets' && <Section title="Monthly budgets" subtitle="Spending targets by category—not forecast expenses." actions={<Button size="sm" disabled={disabled} onClick={() => setBudget('new')}><Plus size={15} /> Add budget</Button>}>{store.plans.budgets.map(b => <div className="finance-row" key={b.id}><div><strong>{store.catalog?.categories.find(c => c.id === b.categoryId)?.name}</strong><p>{displayDate(b.month)}</p></div><div className="finance-actions"><Money book={store.book!} value={b.amountMinor} /><Button variant="ghost" iconOnly size="sm" disabled={disabled} aria-label="Edit budget" tooltip="Edit budget" onClick={() => setBudget(b)}><Pencil size={15} /></Button></div></div>)}{!store.plans.budgets.length && <Empty title="Set a spending target" description="Choose a category, a month and the amount you want to stay within." />}</Section>}
    {view === 'estimates' && <><Section title="Monthly spending estimates" subtitle="For everyday spending that isn’t already covered by a plan." actions={<Button size="sm" disabled={disabled} onClick={() => { setSeed(undefined); setEstimate('new'); }}><Plus size={15} /> Add estimate</Button>}>{store.plans.estimates.map(e => <div className="finance-row" key={e.id}><strong>{store.catalog?.categories.find(c => c.id === e.categoryId)?.name}</strong><div className="finance-actions"><AmountRange book={store.book!} low={e.lowMinor} expected={e.expectedMinor} high={e.highMinor} /><Button variant="ghost" iconOnly size="sm" disabled={disabled} aria-label="Edit estimate" tooltip="Edit estimate" onClick={() => setEstimate(e)}><Pencil size={15} /></Button></div></div>)}{!store.plans.estimates.length && <Empty title="Plan for everyday spending" description="Estimate variable costs such as food, travel and shopping." />}</Section>
      <Section title="Suggestions from your history" subtitle="Check for missing records and bills already in your plans before saving." actions={<Button variant="outlined" size="sm" disabled={store.busy} onClick={() => void store.loadSuggestions()}>Find suggestions</Button>}>{store.suggestions ? <div className="finance-card-body finance-form-stack">{store.suggestions.warnings.map(w => <Alert key={w}>{w}</Alert>)}{store.suggestions.estimates.map(s => <div className="finance-row" key={s.categoryId}><div><strong>{s.categoryName}</strong><p>Spending recorded in {s.monthsWithRecordedSpend} of 6 months</p></div><div className="finance-actions"><AmountRange book={store.book!} low={s.lowMinor} expected={s.expectedMinor} high={s.highMinor} /><Button variant="outlined" size="sm" disabled={disabled} onClick={() => { setSeed(s); setEstimate('new'); }}>Review estimate</Button></div></div>)}{!store.suggestions.estimates.length && <p className="finance-muted">Not enough spending history for suggestions yet.</p>}</div> : <p className="finance-card-body finance-muted">Use your recorded transactions to suggest monthly amounts. Nothing is saved automatically.</p>}</Section></>}
    {view === 'rules' && <Section title="Import rules" subtitle="Suggest categories when a statement description matches." actions={<Button size="sm" disabled={disabled} onClick={() => setRule('new')}><Plus size={15} /> Add rule</Button>}>{store.rules.map(r => <div className="finance-row" key={r.id}><div><strong>Contains “{r.matchText}”</strong><p>{store.catalog?.categories.find(c => c.id === r.categoryId)?.name}{r.merchantName ? ` · ${r.merchantName}` : ''}{!r.enabled ? ' · Disabled' : ''}</p></div><Button variant="ghost" iconOnly size="sm" disabled={disabled} aria-label={`Edit rule ${r.matchText}`} tooltip="Edit rule" onClick={() => setRule(r)}><Pencil size={15} /></Button></div>)}{!store.rules.length && <Empty title="Less sorting, next time" description="Match words in imported descriptions to a category. You’ll review the suggestions before importing." />}</Section>}
    {book && <BookForm store={store} existing={store.book!} onClose={() => setBook(false)} />}{category && <CategoryForm store={store} existing={category === 'new' ? undefined : category} onClose={() => setCategory(null)} />}{budget && <BudgetForm store={store} existing={budget === 'new' ? undefined : budget} onClose={() => setBudget(null)} />}{estimate && <EstimateForm store={store} existing={estimate === 'new' ? undefined : estimate} seed={seed} onClose={() => setEstimate(null)} />}{rule && <RuleForm store={store} existing={rule === 'new' ? undefined : rule} onClose={() => setRule(null)} />}
  </>;
});
function ReconcileForm({ store, onClose }: { store: FinanceStore; onClose: () => void }) {
  const [accountId, setAccount] = useState(''), [date, setDate] = useState(store.today), [balance, setBalance] = useState(''), [notes, setNotes] = useState('');
  return <FormDialog store={store} title="Reconcile a statement" description="Cleared, posted entries must match the statement’s closing balance. No transaction is added to make them match. Confirming locks this account period." onClose={onClose} onSave={async () => !!await store.mutate(() => store.repo.reconcile(store.bookId, { accountId, date, statementBalance: balance, notes }))}><div className="finance-form-stack"><Field label="Account"><Select required value={accountId} onChange={e => setAccount(e.target.value)}><option value="">Choose account</option><AccountOptions store={store} /></Select></Field><Field label="Statement through"><Input required type="date" value={date} onChange={e => setDate(e.target.value)} /></Field><Field label="Statement closing balance"><Input required inputMode="decimal" value={balance} onChange={e => setBalance(e.target.value)} /></Field><Field label="Notes"><Textarea rows={3} value={notes} onChange={e => setNotes(e.target.value)} /></Field></div></FormDialog>;
}
export const HistoryPanel = observer(function HistoryPanel({ store }: { store: FinanceStore }) {
  const [reconcile, setReconcile] = useState(false), [reopen, setReopen] = useState<F.Reconciliation | null>(null), [reason, setReason] = useState('');
  const [view, setView] = useState<'activity' | 'periods'>('activity');
  return <><FinanceHeader store={store} title="History" subtitle="See what changed and check your account statements." actions={<Button size="sm" variant="outlined" disabled={store.readOnly || store.busy} onClick={() => setReconcile(true)}>Reconcile account</Button>} />
    <ViewTabs label="History views" items={[{ id: 'activity', label: 'Activity' }, { id: 'periods', label: 'Account periods' }]} value={view} onChange={setView} />
    {view === 'periods' && <Section title="Reconciled account periods" subtitle="Confirming a statement balance locks that account period. Reopening is recorded in history.">{store.reconciliations.map(r => <div className="finance-row" key={r.id}><div><strong>{store.catalog?.accounts.find(a => a.id === r.accountId)?.name}</strong><p>Through {displayDate(r.date)} · {r.reopenedAt ? 'Reopened' : 'Locked'}</p>{r.notes && <p>{r.notes}</p>}</div><div className="finance-actions"><div className="finance-amount-range"><strong><Money book={store.book!} value={r.statementMinor} /></strong><small>Statement balance</small></div>{!r.reopenedAt && <Button variant="outlined" size="sm" disabled={store.readOnly || store.busy} onClick={() => { setReason(''); setReopen(r); }}>Reopen</Button>}</div></div>)}{!store.reconciliations.length && <Empty title="No reconciled periods yet" description="Check an account’s recorded balance against its statement, then lock the period." />}</Section>}
    {view === 'activity' && <Section title="Recent changes" subtitle={`Dates shown in ${store.book!.timezone}. Expand a change to see the details.`}>{store.changes.items.map(c => <details className="finance-history" key={c.id}><summary><span className="finance-activity-copy"><strong>{auditActionLabels[c.action] ?? c.action} {auditEntityLabels[c.entityType] ?? c.entityType}{changeName(c, store) ? ` · ${changeName(c, store)}` : ''}</strong><small>{displayTimestamp(c.createdAt, store.book!.timezone)} · {auditSourceLabels[c.source] ?? c.source}</small></span></summary><ChangeDetails change={c} store={store} /></details>)}{!store.changes.items.length && <Empty title="No activity yet" description="Changes made here, through imports or by your AI client will appear here." />}{store.changes.nextCursor && <div className="finance-list-actions"><Button variant="outlined" size="sm" disabled={store.loading} onClick={() => void store.moreChanges()}>Load more history</Button></div>}</Section>}
    {reconcile && <ReconcileForm store={store} onClose={() => setReconcile(false)} />}{reopen && <FormDialog store={store} title="Reopen account period?" description="Later reconciliations that depend on this period will also reopen. Transactions and history stay unchanged." onClose={() => setReopen(null)} saveLabel="Reopen" onSave={async () => !!await store.mutate(() => store.repo.reopen(store.bookId, reopen.id, reopen.version, reason))}><Field label="Reason"><Textarea required maxLength={5000} rows={3} value={reason} onChange={e => setReason(e.target.value)} /></Field></FormDialog>}
  </>;
});
