import { useEffect, useState } from 'react';
import { observer } from 'mobx-react-lite';
import { Pencil, Plus, Link2, Unlink } from 'lucide-react';
import { formatMoney } from '@reader/finance-core';
import type * as F from '@domain/finance/models/finance';
import { Button } from '@modules/core/ui/primitives/button';
import type { FinanceStore } from '../store';
import { amountRangeLabels, occurrenceLabel, shortDate, titleCase, transactionKindLabels } from '../format';
import { AccountOptions, CategoryOptions } from './catalog-forms';
import { Alert, Check, Field, FormDialog, Input, Money, Section, Select, Textarea } from './common';

export function RangeFields({ low, expected, high, onChange }: { low: string; expected: string; high: string; onChange: (field: 'low' | 'expected' | 'high', value: string) => void }) {
  return <div className="finance-form-grid">{(['low', 'expected', 'high'] as const).map(field => <Field key={field} label={amountRangeLabels[field]}><Input required inputMode="decimal" value={{ low, expected, high }[field]} onChange={e => onChange(field, e.target.value)} /></Field>)}</div>;
}
export function ScheduleForm({ store, existing, seed, onClose }: { store: FinanceStore; existing?: F.Schedule; seed?: Partial<F.ScheduleFields>; onClose: () => void }) {
  const scale = store.book!.currencyScale;
  const [requestKey] = useState(() => crypto.randomUUID());
  const [fields, setFields] = useState<F.ScheduleFields>(existing ? { title: existing.title, kind: existing.kind, accountId: existing.accountId, destinationAccountId: existing.destinationAccountId, categoryId: existing.categoryId, frequency: existing.frequency, interval: existing.interval, monthEnd: existing.monthEnd, startDate: shortDate(existing.startDate), endDate: existing.endDate ? shortDate(existing.endDate) : null, low: formatMoney(BigInt(existing.lowMinor), scale), expected: formatMoney(BigInt(existing.expectedMinor), scale), high: formatMoney(BigInt(existing.highMinor), scale), notesMarkdown: existing.notesMarkdown, paused: existing.paused } : { title: '', kind: 'EXPENSE', accountId: null, destinationAccountId: null, categoryId: null, frequency: 'MONTHLY', interval: 1, monthEnd: false, startDate: store.today, endDate: null, low: '0', expected: '0', high: '0', paused: false, ...seed });
  const [archived, setArchived] = useState(!!existing?.archivedAt);
  const set = <K extends keyof F.ScheduleFields>(key: K, value: F.ScheduleFields[K]) => setFields(old => ({ ...old, [key]: value }));
  return <FormDialog store={store} title={existing ? 'Edit recurring plan' : 'Add a plan'} wide description="Plans estimate future income and spending; they don’t record transactions. Editing a plan keeps previous bills and payment links." onClose={onClose} onSave={async () => !!await store.mutate(() => existing ? store.repo.updateSchedule(store.bookId, existing.id, { ...fields, expectedVersion: existing.version, archived }) : store.repo.createSchedule(store.bookId, { ...fields, requestKey }))}>
    <div className="finance-form-stack"><div className="finance-form-grid"><Field label="Title"><Input required maxLength={255} value={fields.title} onChange={e => set('title', e.target.value)} /></Field><Field label="Type"><Select value={fields.kind} onChange={e => { set('kind', e.target.value as typeof fields.kind); set('categoryId', null); set('destinationAccountId', null); }}><option value="EXPENSE">Expense</option><option value="INCOME">Income</option><option value="TRANSFER">Transfer</option></Select></Field><Field label="Account"><Select value={fields.accountId ?? ''} onChange={e => set('accountId', e.target.value || null)}><option value="">No account selected</option><AccountOptions store={store} /></Select></Field>{fields.kind === 'TRANSFER' ? <Field label="Destination account"><Select required value={fields.destinationAccountId ?? ''} onChange={e => set('destinationAccountId', e.target.value || null)}><option value="">Choose destination</option><AccountOptions store={store} /></Select></Field> : <Field label="Category"><Select value={fields.categoryId ?? ''} onChange={e => set('categoryId', e.target.value || null)}><option value="">Uncategorized</option><CategoryOptions store={store} kind={fields.kind} /></Select></Field>}<Field label="Repeats"><Select value={fields.frequency} onChange={e => set('frequency', e.target.value as F.Frequency)}>{['ONCE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY'].map(f => <option key={f} value={f}>{titleCase(f)}</option>)}</Select></Field><Field label="Repeat every" hint="Every 28 days differs from once a month."><Input required type="number" min={1} max={10000} value={fields.interval} onChange={e => set('interval', Number(e.target.value))} /></Field><Field label="First due date"><Input required type="date" value={fields.startDate} onChange={e => set('startDate', e.target.value)} /></Field><Field label="Last due date (optional)"><Input type="date" min={fields.startDate} value={fields.endDate ?? ''} onChange={e => set('endDate', e.target.value || null)} /></Field></div><Check label="Use the last day of the month" checked={fields.monthEnd} onChange={value => set('monthEnd', value)} /><RangeFields {...fields} onChange={set} /><p className="finance-note">For fixed amounts, enter the same value in all three fields. For a range, enter low, expected and high values in order—for example, 200, 300 and 400.</p><Field label="Notes (Markdown)"><Textarea rows={3} value={fields.notesMarkdown ?? ''} onChange={e => set('notesMarkdown', e.target.value || null)} /></Field><Check label="Pause future bills" checked={fields.paused} onChange={value => set('paused', value)} />{existing && <Check label="Archive plan" checked={archived} onChange={setArchived} />}</div>
  </FormDialog>;
}
function OccurrenceForm({ store, item, onClose }: { store: FinanceStore; item: F.Occurrence; onClose: () => void }) {
  const [title, setTitle] = useState(item.title), [range, setRange] = useState({ low: formatMoney(BigInt(item.lowMinor), store.book!.currencyScale), expected: formatMoney(BigInt(item.expectedMinor), store.book!.currencyScale), high: formatMoney(BigInt(item.highMinor), store.book!.currencyScale) }), [skip, setSkip] = useState(item.state === 'SKIPPED');
  return <FormDialog store={store} title="Edit this bill" description={`${shortDate(item.date)} · Changes apply only to this bill.`} onClose={onClose} onSave={async () => !!await store.mutate(() => store.repo.updateOccurrence(store.bookId, { scheduleId: item.scheduleId, date: shortDate(item.date), expectedVersion: item.version, title, ...range, state: skip ? 'SKIPPED' : 'OPEN' }))}><div className="finance-form-stack"><Field label="Title"><Input required value={title} onChange={e => setTitle(e.target.value)} /></Field><RangeFields {...range} onChange={(field, value) => setRange(old => ({ ...old, [field]: value }))} /><Check label="Skip this bill" checked={skip} onChange={setSkip} /><p className="finance-note">Link a posted transaction to mark this bill paid. Saving changes doesn’t record a payment.</p></div></FormDialog>;
}
function PaymentForm({ store, item, onClose }: { store: FinanceStore; item: F.Occurrence; onClose: () => void }) {
  const [items, setItems] = useState<F.Transaction[]>([]), [cursor, setCursor] = useState<string | null>(null), [search, setSearch] = useState(''), [loading, setLoading] = useState(false), [error, setError] = useState(''), [movementId, setMovement] = useState(''), [amount, setAmount] = useState(formatMoney(BigInt(item.remainingExpectedMinor), store.book!.currencyScale));
  useEffect(() => { let active = true; setLoading(true); store.repo.transactions(store.bookId, { status: 'POSTED', kind: item.kind, accountId: item.accountId ?? undefined, search: search || undefined, to: store.today, take: 100 }).then(result => { if (!active) return; setLoading(false); if (result.ok) { setItems(result.data.items); setCursor(result.data.nextCursor); } else setError(result.error.message); }); return () => { active = false; }; }, [store, item.kind, item.accountId, search]);
  const more = async () => { if (!cursor) return; setLoading(true); const result = await store.repo.transactions(store.bookId, { status: 'POSTED', kind: item.kind, accountId: item.accountId ?? undefined, search: search || undefined, to: store.today, cursor, take: 100 }); setLoading(false); if (result.ok) { setItems(old => [...old, ...result.data.items]); setCursor(result.data.nextCursor); } else setError(result.error.message); };
  return <FormDialog store={store} title="Link a payment" description={`${item.title} · ${shortDate(item.date)}. You can link partial payments.`} onClose={onClose} onSave={async () => !!await store.mutate(() => store.repo.matchPayment(store.bookId, { scheduleId: item.scheduleId, date: shortDate(item.date), expectedVersion: item.version, movementId, amount }))}><div className="finance-form-stack">{error && <Alert error>{error}</Alert>}<Field label="Search recorded transactions"><Input value={search} onChange={e => setSearch(e.target.value)} /></Field><Field label="Posted account entry"><Select required value={movementId} onChange={e => setMovement(e.target.value)}><option value="">{loading ? 'Loading…' : 'Choose payment'}</option>{items.flatMap(t => t.movements.filter(m => (!item.accountId || m.accountId === item.accountId) && (item.kind === 'INCOME' ? BigInt(m.amountMinor) > 0n : BigInt(m.amountMinor) < 0n)).map(m => <option key={m.id} value={m.id}>{shortDate(m.effectiveDate)} · {t.description} · {formatMoney(BigInt(m.amountMinor), store.book!.currencyScale)}</option>))}</Select></Field>{cursor && <Button type="button" variant="outlined" disabled={loading} onClick={() => void more()}>Load more payments</Button>}<Field label="Payment amount (positive)"><Input required inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} /></Field></div></FormDialog>;
}
export const PlansPanel = observer(function PlansPanel({ store }: { store: FinanceStore }) {
  const [edit, setEdit] = useState<F.Schedule | 'new' | null>(null), [occurrence, setOccurrence] = useState<F.Occurrence | null>(null), [payment, setPayment] = useState<F.Occurrence | null>(null);
  const [unlink, setUnlink] = useState<{ item: F.Occurrence; movementId: string } | null>(null), [seed, setSeed] = useState<Partial<F.ScheduleFields>>();
  return <><Section store={store} title="Plans" subtitle="Plan future bills, income and transfers using fixed amounts or estimates." actions={<Button size="sm" disabled={store.readOnly || store.busy} onClick={() => { setSeed(undefined); setEdit('new'); }}><Plus size={15} /> Add plan</Button>}>
    {store.plans.schedules.map(item => <div className="finance-row" key={item.id}><div><strong>{item.title}</strong><p>{transactionKindLabels[item.kind]} · {titleCase(item.frequency)}{item.interval !== 1 ? ` × ${item.interval}` : ''} · {shortDate(item.startDate)}{item.paused ? ' · Paused' : ''}{item.archivedAt ? ' · Archived' : ''}</p></div><div className="finance-actions"><Money book={store.book!} value={item.lowMinor} /> / <Money book={store.book!} value={item.expectedMinor} /> / <Money book={store.book!} value={item.highMinor} /><Button variant="ghost" size="sm" iconOnly aria-label={`Edit ${item.title}`} disabled={store.readOnly || store.busy} onClick={() => setEdit(item)}><Pencil size={15} /></Button></div></div>)}{!store.plans.schedules.length && <p className="finance-card-body finance-muted">Add a plan for income, a bill, a subscription or a one-off expense.</p>}
  </Section><Section title="Upcoming bills and income" subtitle={`${shortDate(store.reportFrom)} to ${shortDate(store.forecastTo)}. Edit a bill without changing its plan.`}><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Due / bill</th><th>Expected</th><th>Paid / remaining</th><th>Actions</th></tr></thead><tbody>{store.occurrences.map(item => <tr key={`${item.scheduleId}/${item.date}`}><td><strong>{item.title}</strong><small>{shortDate(item.date)} · {occurrenceLabel(item, store.today)}{item.version ? ' · Saved snapshot' : ''}</small></td><td><Money book={store.book!} value={item.expectedMinor} /></td><td><Money book={store.book!} value={item.paidMinor} /> / <Money book={store.book!} value={item.remainingExpectedMinor} /><small>{item.payments.length} payment links</small></td><td><div className="finance-actions"><Button variant="ghost" iconOnly size="sm" disabled={store.readOnly || store.busy} aria-label={`Edit bill ${item.title} ${shortDate(item.date)}`} onClick={() => setOccurrence(item)}><Pencil size={15} /></Button><Button variant="ghost" iconOnly size="sm" disabled={store.readOnly || store.busy || item.state === 'SKIPPED'} aria-label={`Link payment to ${item.title}`} onClick={() => setPayment(item)}><Link2 size={15} /></Button>{item.payments.map(p => <Button key={p.movementId} variant="ghost" iconOnly size="sm" disabled={store.readOnly || store.busy} aria-label={`Unlink payment ${p.movementId}`} onClick={() => setUnlink({ item, movementId: p.movementId })}><Unlink size={15} /></Button>)}</div></td></tr>)}</tbody></table></div></Section>
  {store.suggestions && <Section title="Suggested plans" subtitle="Based on recorded transactions. Nothing is added until you review and save."><div className="finance-card-body finance-form-stack">{store.suggestions.warnings.map(w => <Alert key={w}>{w}</Alert>)}{store.suggestions.recurring.map((s, index) => <div className="finance-row" key={index}><div><strong>{s.title}</strong><p>{s.reason} · Last recorded {s.lastRecordedDate}</p></div><Button variant="outlined" size="sm" disabled={store.readOnly} onClick={() => { setSeed({ title: s.title, accountId: s.accountId, categoryId: s.categoryId, frequency: s.frequency, interval: s.interval, startDate: store.today, low: formatMoney(BigInt(s.lowMinor), store.book!.currencyScale), expected: formatMoney(BigInt(s.expectedMinor), store.book!.currencyScale), high: formatMoney(BigInt(s.highMinor), store.book!.currencyScale) }); setEdit('new'); }}>Review as plan</Button></div>)}</div></Section>}
  {edit && <ScheduleForm store={store} existing={edit === 'new' ? undefined : edit} seed={seed} onClose={() => setEdit(null)} />}{occurrence && <OccurrenceForm store={store} item={occurrence} onClose={() => setOccurrence(null)} />}{payment && <PaymentForm store={store} item={payment} onClose={() => setPayment(null)} />}{unlink && <FormDialog store={store} title="Remove payment link?" description={unlink.item.title} onClose={() => setUnlink(null)} onSave={async () => !!await store.mutate(() => store.repo.unmatchPayment(store.bookId, { scheduleId: unlink.item.scheduleId, date: shortDate(unlink.item.date), expectedVersion: unlink.item.version, movementId: unlink.movementId }))}><p>The transaction stays unchanged. This amount will show as unpaid on the bill.</p></FormDialog>}
  </>;
});
