import { useState } from 'react';
import { Download } from 'lucide-react';
import { Popover } from '@modules/core/ui/primitives/popover';
import { observer } from 'mobx-react-lite';
import { Button } from '@modules/core/ui/primitives/button';
import type { FinanceStore } from '../store';
import { Alert, FinanceHeader, Field, Input, Money, PeriodForm, Section } from './common';
import { downloadExport, shortDate } from '../format';

export const ReportsPanel = observer(function ReportsPanel({ store, overview = false }: { store: FinanceStore; overview?: boolean }) {
  const report = store.report, book = store.book!;
  const [exportOpen, setExportOpen] = useState(false);
  const exportFile = async (format: 'JSON' | 'CSV') => { const result = await store.mutate(() => store.repo.export(store.bookId, format === 'JSON' ? { format, includeDeleted: true } : { format, from: store.reportFrom, to: store.reportTo }), 'Export downloaded'); if (result) downloadExport(result.filename, result.mime, result.content); };
  return <><FinanceHeader title={overview ? 'Overview' : 'Reports'} subtitle={`${book.name} · ${book.currency} · ${book.timezone}`} store={store} actions={<Popover open={exportOpen} onOpenChange={setExportOpen} align="end" content={<div className="finance-export-menu"><Button variant="ghost" size="sm" disabled={store.busy} onClick={() => { setExportOpen(false); void exportFile('CSV'); }}>Period CSV</Button><Button variant="ghost" size="sm" disabled={store.busy} onClick={() => { setExportOpen(false); void exportFile('JSON'); }}>Full book (JSON)</Button></div>}><Button variant="outlined" size="sm" disabled={store.busy}><Download size={14} aria-hidden="true" /> Export</Button></Popover>} /><PeriodForm key={`${store.reportFrom}/${store.reportTo}`} from={store.reportFrom} to={store.reportTo} onApply={store.setPeriod} />
    {report && <><div className="finance-stats">{[['Income', report.totals.incomeMinor], ['Spending after refunds', report.totals.netSpendingMinor], ['Income less spending', report.totals.netIncomeMinor], ['Net cash movement', report.cashFlow.netMinor]].map(([label, value]) => <div className="finance-stat" key={label}><div className="finance-stat-label">{label}</div><div className="finance-stat-value"><Money book={book} value={value} /></div><small>{shortDate(report.from)} – {shortDate(report.to)}</small></div>)}</div>
      {report.warnings.map(warning => <Alert key={warning}>{warning}</Alert>)}<div className="finance-grid"><Section title="Account balances" subtitle={`Posted account entries through ${shortDate(report.to)}. Debt doesn’t count as income.`}>{report.balances.map(item => <div className="finance-row" key={item.id}><div><strong>{item.name}</strong><p>{item.isLiquid ? 'Available cash account' : 'Not available cash'}{item.archivedAt ? ' · Archived' : ''}</p></div><Money book={book} value={item.postedMinor} color /></div>)}</Section><Section title="Category spending and income" subtitle="Parent category totals include subcategories. Don’t add both totals together.">{report.categories.filter(c => BigInt(c.rollupMinor) !== 0n).map(item => <div className="finance-row" key={item.id}><div><strong>{item.name}</strong><p>{item.kind === 'INCOME' ? 'Income' : 'Spending after refunds'}{item.parentId ? ' · Subcategory' : ''}</p></div><Money book={book} value={item.rollupMinor} /></div>)}<div className="finance-row"><span>Uncategorized spending / income</span><span><Money book={book} value={report.unclassifiedExpenseMinor} /> / <Money book={book} value={report.unclassifiedIncomeMinor} /></span></div></Section></div>
      <Section title="Budgets" subtitle="Budgets are targets, not forecasts. Spending shown here includes refunds.">{report.budgetStatus.length ? report.budgetStatus.map(item => <div className="finance-row" key={item.id}><div><strong>{item.categoryName} · {item.month.slice(0, 7)}</strong><p>{item.partialMonth ? 'Partial-month actuals' : 'Full month'} · Spent <Money book={book} value={item.spentMinor} /> of <Money book={book} value={item.amountMinor} /></p></div><span>Remaining <Money book={book} value={item.remainingMinor} color /></span></div>) : <p className="finance-card-body finance-muted">Add budgets in Manage.</p>}</Section>
      {!overview && <><div className="finance-grid">{[['Merchants', report.merchants], ['Payment methods', report.paymentMethods]].map(([title, entries]) => <Section key={String(title)} title={String(title)}>{(entries as typeof report.merchants).map(item => <div className="finance-row" key={item.name}><strong>{item.name || 'Not specified'}</strong><Money book={book} value={item.amountMinor} /></div>)}</Section>)}</div>{report.comparison && <Section title="Previous period (same number of days)" subtitle={`${shortDate(report.comparison.from)} – ${shortDate(report.comparison.to)}`}><div className="finance-row"><span>Income change</span><Money book={book} value={report.comparison.incomeChangeMinor} color /></div><div className="finance-row"><span>Spending change</span><Money book={book} value={report.comparison.spendingChangeMinor} /></div></Section>}<Section title="Data quality" subtitle="Reports include only the data you’ve recorded."><div className="finance-card-body finance-form-stack"><p>{report.quality.uncategorizedTransactionCount} uncategorized · {report.quality.pendingCount} pending · {report.quality.unclearedMovementCount} uncleared entries</p><p>{report.quality.unverifiedImportCount} unverified statement imports · {report.quality.archivedAccountsWithBalance.length} archived accounts with balances</p></div></Section></>}
    </>}
    {overview && <ForecastPanel store={store} />}
  </>;
});
export const ForecastPanel = observer(function ForecastPanel({ store }: { store: FinanceStore }) {
  const forecast = store.forecast, book = store.book!;
  const monthly = forecast?.timeline.filter((day, index, timeline) => !timeline[index + 1] || timeline[index + 1].date.slice(0, 7) !== day.date.slice(0, 7)) ?? [];
  return <Section title="Cash forecast" subtitle="Estimated cash after planned bills, income and spending estimates. Budgets aren’t included." actions={<Field label="Forecast through"><Input type="date" min={store.today} value={store.forecastTo} onChange={e => { if (e.target.value) store.setForecastTo(e.target.value); }} /></Field>}>
    <div className="finance-card-body finance-form-stack">{store.forecastError && <Alert error>{store.forecastError}</Alert>}{forecast && <><p className="finance-note">Starting from {shortDate(forecast.asOf)}. {forecast.scenarios}</p>{forecast.firstNegativeLowDate && <Alert error>Possible cash shortfall from {shortDate(forecast.firstNegativeLowDate)}{forecast.firstNegativeExpectedDate ? `; expected scenario from ${shortDate(forecast.firstNegativeExpectedDate)}` : ''}.</Alert>}{forecast.overdue.length > 0 && <Alert>{forecast.overdue.length} overdue unpaid bills are included from today.</Alert>}{forecast.warnings.map(w => <p className="finance-note" key={w}>{w}</p>)}<table className="finance-table"><thead><tr><th>Month ending</th><th>Low estimate</th><th>Expected</th><th>High estimate</th></tr></thead><tbody>{monthly.map(day => <tr key={day.date}><td>{shortDate(day.date)}</td><td><Money book={book} value={day.lowMinor} color /></td><td><Money book={book} value={day.expectedMinor} color /></td><td><Money book={book} value={day.highMinor} color /></td></tr>)}</tbody></table><details><summary>Daily and per-account forecast</summary><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Date</th><th>Expected estimate</th><th>Expected balance by account</th><th>Events</th></tr></thead><tbody>{forecast.timeline.map(day => <tr key={day.date}><td>{shortDate(day.date)}</td><td><Money book={book} value={day.expectedMinor} color /></td><td>{day.accounts.map(account => <small key={account.accountId}>{store.catalog?.accounts.find(a => a.id === account.accountId)?.name ?? 'Estimates with no account'}: <Money book={book} value={account.expectedMinor} /></small>)}</td><td>{day.events.map((event, index) => <small key={index}>{event.title}{event.overdue ? ' · Overdue' : ''}</small>)}</td></tr>)}</tbody></table></div></details></>}</div>
  </Section>;
});
