import { useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { formatMoney } from '@reader/finance-core';
import type * as F from '@domain/finance/models/finance';
import { Button } from '@modules/core/ui/primitives/button';
import type { FinanceStore } from '../store';
import { AccountOptions, CategoryOptions } from './catalog-forms';
import { Alert, Check, Field, FormDialog, Input, Select, Textarea } from './common';
import { simpleMovements } from '../transaction-draft';
export function TransactionForm({ store, existing, onClose }: { store: FinanceStore; existing?: F.Transaction; onClose: () => void }) {
  const scale = store.book!.currencyScale;
  const [requestKey] = useState(() => crypto.randomUUID());
  const [kind, setKind] = useState<F.TransactionKind>(existing?.kind ?? 'EXPENSE'), [status, setStatus] = useState<'POSTED' | 'PENDING'>(existing?.status ?? 'POSTED');
  const [date, setDate] = useState(existing?.date.slice(0, 10) ?? store.today), [description, setDescription] = useState(existing?.description ?? '');
  const [merchant, setMerchant] = useState(existing?.merchant ?? ''), [method, setMethod] = useState(existing?.paymentMethod ?? ''), [reference, setReference] = useState(existing?.bankReference ?? '');
  const [notes, setNotes] = useState(existing?.notesMarkdown ?? ''), [tags, setTags] = useState(existing?.tags.join(', ') ?? ''), [refundOf, setRefundOf] = useState(existing?.refundOfId ?? '');
  const [advanced, setAdvanced] = useState(!!existing), [account, setAccount] = useState(store.activeAccounts[0]?.id ?? ''), [destination, setDestination] = useState(''), [amount, setAmount] = useState(''), [cleared, setCleared] = useState(false);
  const [movements, setMovements] = useState<F.TransactionFields['movements']>(existing?.movements.map(m => ({ accountId: m.accountId, amount: formatMoney(BigInt(m.amountMinor), scale), effectiveDate: m.effectiveDate.slice(0, 10), cleared: m.cleared })) ?? []);
  const [splits, setSplits] = useState(existing?.splits.map(s => ({ categoryId: s.categoryId, amount: formatMoney(BigInt(s.amountMinor), scale) })) ?? []);
  const protect = existing?.movements.some(m => m.reconciliationId || m.sourceRecords.length || m.payments.length);
  const [draftError, setDraftError] = useState('');
  const toAdvanced = () => { try { setMovements(simpleMovements(kind, amount, account, destination, date, cleared, scale)); setAdvanced(true); setDraftError(''); } catch (cause) { setDraftError((cause as Error).message); } };
  return <FormDialog store={store} title={existing ? 'Edit transaction' : 'Add transaction'} wide description="Transfers don’t count as income or spending. Changes are saved in history." onClose={onClose} onSave={async () => {
    const input: F.TransactionFields = { kind, status, date, description, merchant: merchant || null, paymentMethod: method || null, bankReference: reference || null, notesMarkdown: notes || null, tags: tags.split(',').map(s => s.trim()).filter(Boolean), refundOfId: kind === 'REFUND' ? refundOf || null : null, movements: advanced ? movements : simpleMovements(kind, amount, account, destination, date, cleared, scale), splits: kind === 'TRANSFER' || kind === 'ADJUSTMENT' ? [] : splits };
    return !!await store.mutate(() => existing ? store.repo.updateTransaction(store.bookId, existing.id, { ...input, expectedVersion: existing.version }) : store.repo.createTransaction(store.bookId, { ...input, requestKey }));
  }}><div className="finance-form-stack">{draftError && <Alert error>{draftError}</Alert>}{protect && <Alert>Some account entries are protected. You can edit descriptions and categories. Remove payment links or reopen reconciled periods before changing protected amounts, dates or accounts. Imported entries require a separate correction.</Alert>}
    <h3 className="finance-form-heading">Transaction</h3><div className="finance-form-grid"><Field label="Description"><Input required maxLength={1000} placeholder="What was it for?" value={description} onChange={e => setDescription(e.target.value)} /></Field><Field label="Date"><Input type="date" required value={date} onChange={e => setDate(e.target.value)} /></Field><Field label="Type"><Select value={kind} onChange={e => { setKind(e.target.value as F.TransactionKind); setSplits([]); }}><option value="EXPENSE">Expense</option><option value="INCOME">Income</option><option value="TRANSFER">Transfer</option><option value="REFUND">Expense refund</option><option value="ADJUSTMENT">Balance correction</option></Select></Field><Field label="Status"><Select value={status} onChange={e => setStatus(e.target.value as typeof status)}><option value="POSTED">Posted</option><option value="PENDING">Pending</option></Select></Field></div>
    <h3 className="finance-form-heading">Account and amount</h3>
    {!advanced ? <><div className="finance-form-grid"><Field label="Account"><Select required value={account} onChange={e => setAccount(e.target.value)}><option value="">Choose account</option><AccountOptions store={store} /></Select></Field><Field label={kind === 'ADJUSTMENT' ? 'Balance change (+ or −)' : 'Amount'}><Input required inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} /></Field>{kind === 'TRANSFER' && <Field label="To account"><Select required value={destination} onChange={e => setDestination(e.target.value)}><option value="">Choose destination</option><AccountOptions store={store} /></Select></Field>}</div><Check label="Cleared on a statement or confirmed in cash" checked={cleared} onChange={setCleared} /><Button type="button" variant="ghost" size="sm" onClick={toAdvanced}>Enter account changes separately (e.g. loan repayment)</Button></> : <><p className="finance-note">Positive amounts add money; negative amounts remove it. Transfers must total zero. For loan repayments, record the cash paid and debt reduced; only interest counts as spending.</p>{movements.map((m, i) => <div className="finance-form-grid" key={i}><Field label={`Account ${i + 1}`}><Select required value={m.accountId} onChange={e => setMovements(rows => rows.map((row, index) => index === i ? { ...row, accountId: e.target.value } : row))}><option value="">Choose account</option><AccountOptions store={store} includeArchived /></Select></Field><Field label="Amount (+ or −)"><Input required inputMode="decimal" value={m.amount} onChange={e => setMovements(rows => rows.map((row, index) => index === i ? { ...row, amount: e.target.value } : row))} /></Field><Field label="Effective date"><Input required type="date" value={m.effectiveDate ?? date} onChange={e => setMovements(rows => rows.map((row, index) => index === i ? { ...row, effectiveDate: e.target.value } : row))} /></Field><div className="finance-actions"><Check label="Cleared" checked={m.cleared} onChange={value => setMovements(rows => rows.map((row, index) => index === i ? { ...row, cleared: value } : row))} /><Button type="button" variant="ghost" iconOnly aria-label={`Remove account entry ${i + 1}`} onClick={() => setMovements(rows => rows.filter((_, index) => index !== i))}><Trash2 size={15} /></Button></div></div>)}<Button type="button" variant="outlined" size="sm" disabled={movements.length >= 20} onClick={() => setMovements(rows => [...rows, { accountId: '', amount: '', effectiveDate: date, cleared: false }])}><Plus size={14} /> Add account entry</Button></>}
    {(kind === 'EXPENSE' || kind === 'INCOME' || kind === 'REFUND') && <><p className="finance-note">Split the amount across categories if needed. The remainder stays uncategorized. Use positive amounts for income and expenses, and negative amounts for refunds.</p>{splits.map((split, i) => <div className="finance-split-row" key={i}><Field label={`Category ${i + 1}`}><Select required value={split.categoryId} onChange={e => setSplits(rows => rows.map((row, index) => index === i ? { ...row, categoryId: e.target.value } : row))}><option value="">Choose category</option><CategoryOptions store={store} kind={kind === 'INCOME' ? 'INCOME' : 'EXPENSE'} /></Select></Field><Field label="Amount"><Input inputMode="decimal" required value={split.amount} onChange={e => setSplits(rows => rows.map((row, index) => index === i ? { ...row, amount: e.target.value } : row))} /></Field><Button type="button" iconOnly variant="ghost" aria-label={`Remove category ${i + 1}`} onClick={() => setSplits(rows => rows.filter((_, index) => index !== i))}><Trash2 size={14} /></Button></div>)}<Button type="button" variant="outlined" size="sm" onClick={() => setSplits(rows => [...rows, { categoryId: '', amount: '' }])}><Plus size={14} /> Add category split</Button></>}
    <h3 className="finance-form-heading">Extra details (optional)</h3><div className="finance-form-grid"><Field label="Merchant"><Input maxLength={255} value={merchant} onChange={e => setMerchant(e.target.value)} /></Field><Field label="Payment method" hint="e.g. Cash, UPI, Card"><Input maxLength={100} value={method} onChange={e => setMethod(e.target.value)} /></Field><Field label="Bank reference"><Input maxLength={255} value={reference} onChange={e => setReference(e.target.value)} /></Field><Field label="Tags (comma-separated)"><Input value={tags} onChange={e => setTags(e.target.value)} /></Field>{kind === 'REFUND' && <Field label="Original expense ID (optional)"><Input value={refundOf} onChange={e => setRefundOf(e.target.value)} placeholder="Transaction ID from its details" /></Field>}</div><Field label="Notes"><Textarea rows={4} maxLength={100000} value={notes} onChange={e => setNotes(e.target.value)} /></Field>
  </div></FormDialog>;
}
